### ISSUE TITLE
Implement FAT Actions around Process Wrapper

### ISSUE THREAD

**Issue by frrist** [filecoin-project/venus#1629]
### Description
Once #1628 is complete a higher level set of wrapper methods herein referred to as **Actions** will need to be created that call the Process Wrapper. These Action will serve as a way to execute a Filecoin CLI command. Some examples of actions include:
- `ClientCat`
- `ClientProposeStorageDeal`
- `MinerCreate`
- `MinerAddAsk`

### Acceptance criteria
- Implement Actions for all go-filecoin CLI commands
- Action methods must accept:
  - `context.Context`
  - arguments as concrete types: `address.Address`, `peer.ID`, `types.AttoFIL`, etc.
  - options as [Functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis)
- Actions must return a concrete type and an error.

Required Commands:
- [x] `wallet` & `address` actions: https://github.com/filecoin-project/go-filecoin/issues/1666
- [x] `client` & `retrieval-client` actions: https://github.com/filecoin-project/go-filecoin/issues/1667
- [x] `miner` & `mining` actions: https://github.com/filecoin-project/go-filecoin/issues/1668
- [x]  `chain` actions: https://github.com/filecoin-project/go-filecoin/issues/1669
- [x]  `dag` & `show` & `id` actions: https://github.com/filecoin-project/go-filecoin/issues/1670
- [x]  `bootstrap` actions: https://github.com/filecoin-project/go-filecoin/issues/1671
- [x]  `ping` & `swarm` actions: https://github.com/filecoin-project/go-filecoin/issues/1672
- [x]  `actor` actions: https://github.com/filecoin-project/go-filecoin/issues/1673
- [x]  `paych` actions: https://github.com/filecoin-project/go-filecoin/issues/1674

### Risks + pitfalls
When running an action like `ChainLS` the returned type may be too large, we defer this complexity to the filecoin api -- it must provide "sane" options to make running commands like this easy. i.e. something like a `--limit` option, or pagination.
