### ISSUE TITLE
Proofs

### ISSUE THREAD

**Issue by porcuquine** [filecoin-project/venus#435]
# Proofs

- Trivial PR just needs merging: #430 
- Move proof code into own repo -- somewhat involved and intertwined with [ mmap/streaming seal](https://github.com/filecoin-project/paper-porep-drg/issues/4): #434 
- Master plan for evolution of proofs. This needs to be broken out into individual issues: https://github.com/filecoin-project/go-proofs/issues/1. As that happens, the issues should be structured, prioritized, and added here. The `go-proofs` epic will remain open as a long-term tracking issue. Individual stories will be linked here for project-management purposes.
## [go-proofs](https://github.com/filecoin-project/go-proofs/issues/)
  - [ ] [ Update the APIs of the DRG porep](https://github.com/filecoin-project/go-proofs/issues/7)
  - [ ] After this issue completes, a concrete development task should be spawned:
    - [ ] [Write a pseudocode PoSt and implementation workplan #8]( https://github.com/filecoin-project/go-proofs/issues/8)
    - [x] [Add our own merkle tree implementation](https://github.com/filecoin-project/go-proofs/issues/9)
    - [x] [Add top-level proofs CLI](https://github.com/filecoin-project/go-proofs/issues/10)
    - [ ] [SNARK wrapper](https://github.com/filecoin-project/go-proofs/issues/16)
## [snark-circuits](https://github.com/filecoin-project/snark-circuits/issues/)
- [Structure and Setup](https://github.com/filecoin-project/snark-circuits/issues/7)
  - [ ] [Add Bellman Glue](https://github.com/filecoin-project/snark-circuits/issues/11)

QED
