### ISSUE TITLE
Sprint 42

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4909]
## 背景

仿照[0.3.0](https://github.com/ipfs-force-community/venus-cluster/issues/149)建立`Sprint 42`卡片合集。

sprint日期：6/13 - 6/27
代码审阅：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)
文档建立：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)

## 目标

- [x] go-fvm-sdk优化代码编译编写测试流程，编写quick start文档。
- [ ] NV16 Calib网络发版/测试 (90%)
- [x] miner重构
- [x] market现有issue解决（6-7），并发版
- [x] cluster跟进nv16升级，分支跟进，选择版本合并（0.3.0-rc2/0.4.0主分支基于nv16）
- [x] cluster0.4.0 部分开发 (milestone 0.4.0)
- [ ] 对repo规范化[设置](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/github/%E8%AE%BE%E7%BD%AE)：统一主要repo设置规范，参见下面`通用`栏

## 链服务

- [x] #4917
- [ ] https://github.com/filecoin-project/venus/issues/4904
- [x] https://github.com/filecoin-project/venus/issues/4895
- [ ] https://github.com/filecoin-project/venus/issues/4894

## 订单服务

- [x] https://github.com/filecoin-project/venus/issues/4908
- [ ] https://github.com/filecoin-project/venus/issues/4907
- [ ] https://github.com/filecoin-project/venus/issues/4906
- [ ] https://github.com/filecoin-project/venus/issues/4910
- [x] #4925

## 算力服务

参见[这里](https://github.com/ipfs-force-community/venus-cluster/issues)。

## venus

- [x] #4924
- [x] #4937
- [x] #4936
- [x] #4939

## venus-messager 

- [ ] #4926
- [ ] #4934

## venus-gateway

- [x] #4935

## venus-sealer

- [x] #4927
- [ ] 发布 cali 网络版本

## venus-miner

- [x] https://github.com/filecoin-project/venus/issues/4913
- [ ] https://github.com/filecoin-project/venus/issues/4914
- [x] https://github.com/filecoin-project/venus/issues/4915
- [x] #4930

## go-fvm-sdk
- [ ] #4918
- [ ] 支持合约接口自动生成请求体和返回体的marshal/unmarshal方法， 自动生成go版本客户端代码
- [ ] quick start文档

## 通用
- [ ] 为所有 venus 关联的主要 repo 增加pr检查项（github-actions）配置，保护分支配置
  1. 必须包含编译、测试、代码规范相关的命令，但是可以只做输出（warnings），不中断流程
  2. 测试用例标准罗列（不需要测试的用例）
  3. 所有项目必须统一
  4. PR检查规范（分支是否自己自动删除，[保护分支](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/github/%E8%AE%BE%E7%BD%AE/%E5%88%86%E6%94%AF%E4%BF%9D%E6%8A%A4%E8%A7%84%E5%88%99.md)？）
- [x] #4933

## cali 网络升级清单及测试

- [ ] https://github.com/filecoin-project/venus/discussions/4898

## 社区

- [ ] 根据[模版](https://github.com/filecoin-project/lotus/discussions/8346#discussioncomment-2877098)建立自己的测试项
- [ ] go-fvm-sdk 进一步review，并PR filecoin-project devgrants
- [ ] STM kickoff
- [ ] github project 使用规范
