### ISSUE TITLE
Sprint 43

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#4972]
## 背景

sprint日期：6/27 - 7/08
代码审阅：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)
文档建立：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)

> 上个[sprint](https://github.com/filecoin-project/venus/issues/4909)

## 目标
- [x] venus-cluster 完成 v0.4.0 10个 issue
  - [ ] 降低使用门槛
  - [ ] 提供自定义入口
  - [ ] 开始少量开源的算法定制
- [ ] 确认主要代码库的配置合理，包括 actions (上个[sprint](https://github.com/filecoin-project/venus/issues/4909)中`通用`部分)
- [ ] 确定对于已经稳定的代码库，新提交 issue 关于测试用例的最低要求 (上个sprint中`测试用例`部分；util，fix)
- [ ] 确定venus各组件nv16升级的代码，调整文档，发布v1.6.0 (还缺少文档调整)
- [ ] venus-market 完成10个 issue （完成4个）
- [x] venus-market 检索支持；RootCID检索支持；
- [x] venus v1.17.0 分支pr引入；venus-miner issues（详见下面）（待讨论：看看lotus有没有进master） 
- [x] 监控metrics调研；公共组件？
- [x] github project管理规范 (待review)
- [x] 团队熟悉fvm项目，提交2个PR

### 项目规范化
`Venus` 组件有相对一致的CI/CD:

- [ ] pr流程,如删除原分支，至少有一个approved，所有检查项通过，保护分支不能直接提交commits等；
- [ ] 按照发版规范设定保护分支；
- [ ] pr检查项是否完备，如 gofmt, 单元测试, 覆盖率显示等;
- [ ] 提交 issue, pr 模板是否统一;
- [ ] dependabot alerts 统一;

### venus
v1.7.0 分支
- [ ] https://github.com/filecoin-project/venus/issues/4931
- [ ] #4987
  
v1.6.*分支
- [x] https://github.com/filecoin-project/venus/issues/4977
- [x] https://github.com/filecoin-project/venus/issues/4978
- [ ] 给运维的升级流程文档

### venus-miner
v1.7.0 分支
- [ ] 优化项：
  - [ ] 增加 warmup 命令(https://github.com/filecoin-project/venus/issues/4904)
  - [ ] 获得出块权时在数据库产生记录,后续更新记录(https://github.com/filecoin-project/venus/issues/4919)
- [ ] 新需求:
  - [ ] 引入metrics,包含必要的文档(https://github.com/filecoin-project/venus/issues/4960) 
  - [ ] 引入JaegerTracing,包含必要文档(https://github.com/filecoin-project/venus/issues/4959)
  
v1.6.*分支
- [ ] 主网版本

### venus-market
Bug: 
- [ ] https://github.com/filecoin-project/venus/issues/4906
- [ ] https://github.com/filecoin-project/venus/issues/4943

优化项:
- [ ] https://github.com/filecoin-project/venus/issues/4907
- [ ] https://github.com/filecoin-project/venus/issues/4952
- [ ] https://github.com/filecoin-project/venus/issues/4953
- [ ] https://github.com/filecoin-project/venus/issues/4958
- [ ] https://github.com/filecoin-project/venus/issues/4968
- [x] https://github.com/filecoin-project/venus/issues/4970

piece store:
- [x] https://github.com/filecoin-project/venus/issues/4910
- [ ] https://github.com/filecoin-project/venus/issues/4911
