### ISSUE TITLE
Sprint 45

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5125]
## 背景

sprint日期：7/25 - 8/05
Github Project：[面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)
代码审阅：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)
代码检查项：[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)
文档建立：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)
组件发版：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5046)

## 目标

- [x] fip0029完善 (Lotus团队review)
- [ ] venus-cluster
  - [x] 完成 PoSter 重构实现
  - [x] 完成 metrics 基础框架的引入
  - [x] 完成 扇区重建 功能的设计
  - [x] 翻译2篇英语文档
  - [x] venus-cluster推广教育
- [ ] Q3Q4研发目标[制定](https://github.com/filecoin-project/venus/discussions/5062) 
- [ ] 确定对于已经稳定的代码库，新提交 issue 关于测试用例的最低要求 (上个sprint中测试用例部分；util，fix) （60%-70%）
- [ ] STM系统切分，venus catalog review
- [ ] 需求整理流程文档PR至devguidance
- [x] #5142
- [x] venus-auth 单元测试+接口测试
- [x] prometheus + gragana 指标[监控](https://github.com/s0nik42/lotus-farcaster)系列文档（venus-docs project）
- [ ] venus-miner 核心功能单元测试（80%）
- [x] fvm把对tinygo/go标准库的改造形成patch补丁，通过补丁的方式来做开发，而不是直接维护完整的tinygo仓库
- [ ] venus-market 重构代码地址账号及相关逻辑draft版本/设计/讨论（publish订单聚合方式， fundmgr资产聚合方式 聚合方式使用地址和账号）（问题总结，设计待讨论，50%）
- [ ] venus-market 
   - [x] https://github.com/filecoin-project/venus/issues/5088
- [ ] 完成至少12个非上述所列相关的issues (差2个)
  - [x] https://github.com/filecoin-project/venus/issues/5127
  - [x] https://github.com/filecoin-project/venus/issues/5109
  - [x] https://github.com/filecoin-project/venus/issues/5075
  - [x] https://github.com/filecoin-project/venus/issues/5095
  - [x] https://github.com/filecoin-project/venus/issues/5105
  - [x] https://github.com/filecoin-project/venus/issues/5128
  - [x] https://github.com/filecoin-project/venus/issues/5149
- [ ] issue 精细化管理（形成文档）：约定以下情形的处理流程(初期可以制定简单粗暴的规则：比如谁提的谁去做，或者提的人认为应该和谁一起解决，要是说不出来就自己解决；其他...)
  - [ ] 已经被assign但是长期（超过两个sprint？）没结果的如何处理（https://github.com/filecoin-project/venus/issues/5008）
  - [ ] 提了长期没人接的如何处理（https://github.com/filecoin-project/venus/issues/5024）
  - [ ] 提交issue必要的约定：不重复提交，必要的描述，自己认为有意义的见解等 ... ...

issue 优先选择: (下面所列为特别提醒，貌似存在没人理的可能)
   - [ ] https://github.com/filecoin-project/venus/issues/5051
   - [x] https://github.com/filecoin-project/venus/issues/5036
   - [x] https://github.com/filecoin-project/venus/issues/5024
   - [ ] https://github.com/filecoin-project/venus/issues/5002
   - [x] https://github.com/filecoin-project/venus/issues/4968
