### ISSUE TITLE
[合作] Integration with Farcaster Planning

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5156]
## Background

To explore opportunities of integration with Farcaster so that Venus community could enjoy a open-source solution for better monitoring their storage systems.

## Research

- [ ] https://github.com/filecoin-project/venus/issues/5137

### Week 1

- [x] Access to Venus chain service on calibration
- [x] List of Lotus API that farcaster uses
- [x] Mapping of Lotus APIs with Venus APIs
- [x] List of metrics Venus currently have 

### Week 2

- [ ] Grant proposal draft and review

**Comment by Fatman13** [comment]
## List of metrics (In active development)

- [ ] venus-miner
- [ ] venus-messager
- [ ] venus-gateway
- [ ] venus-market
- [ ] venus

## venus-miner

List of metrics could be found [here](https://github.com/filecoin-project/venus-miner/blob/master/lib/metrics/metrics.go). The wording might need some polish. Note that metrics below are available per miner_id.

```go
         // latency for GetBaseInfo API
	GetBaseInfoDuration   = stats.Float64("getbaseinfo_ms", "Duration of GetBaseInfo in miner", stats.UnitMilliseconds)
        // latency for ComputeTicket API
	ComputeTicketDuration = stats.Float64("computeticket_ms", "Duration of ComputeTicket in miner", stats.UnitMilliseconds)
        // latency for IsRoundWinner API
	IsRoundWinnerDuration = stats.Float64("isroundwinner_ms", "Duration of IsRoundWinner in miner", stats.UnitMilliseconds)
        // latency for ComputeProof API
	ComputeProofDuration  = stats.Float64("computeproof_s", "Duration of ComputeProof in miner", stats.UnitSeconds)

        // number of block produced
	NumberOfBlock         = stats.Int64("number_of_block", "Number of production blocks", stats.UnitDimensionless)
        // number of rounds that miner_id is winner
	NumberOfIsRoundWinner = stats.Int64("number_of_isroundwinner", "Number of is round winner", stats.UnitDimensionless)
```

**Comment by s0nik42** [comment]
# List of metrics used by farcaster (REST API) :

## Lotus node
ChainHead
MinerGetBaseInfo
MpoolPending
NetBandwidthStats
NetBandwidthStatsByProtocol
NetPeers
StateAccountKey
StateActorCodeCIDs
StateGetActor
StateLookupID
StateMarketStorageDeal
StateMinerAvailableBalance
StateMinerDeadlines
StateMinerInfo
StateMinerPartitions
StateMinerPower
StateMinerProvingDeadline
StateNetworkName
StateNetworkVersion
StateReadState
StateVerifiedClientStatus
SyncState
Version
WalletBalance
WalletList

## Lotus miner
ActorAddress
SealingSchedDiag
SectorsList
SectorsStatus
StorageInfo
StorageList
StorageLocal
StorageStat
Version
WorkerJobs
WorkerStats

## Lotus markets/boost
DealsConsiderOfflineRetrievalDeals
DealsConsiderOfflineStorageDeals
DealsConsiderOnlineRetrievalDeals
DealsConsiderOnlineStorageDeals
MarketGetAsk
MarketGetRetrievalAsk
MarketListDataTransfers
NetBandwidthStats
NetBandwidthStatsByProtocol
NetPeers

**Comment by Fatman13** [comment]
@diwufeiwen 大神，有空的时候麻烦看看api的对应关系。🙏

**Comment by Fatman13** [comment]
# List of metrics used by farcaster (REST API) :

## test

```
# ChainHead
curl http://<IP>:<PORT>/rpc/v1 -X POST -H "Content-Type: application/json"  -H "Authorization: Bearer <token>"  -d '{"method": "Filecoin.ChainHead","params":[], "id": 0}'
```

## Lotus node -> venus node


ChainHead

MinerGetBaseInfo

MpoolPending

NetBandwidthStats

NetBandwidthStatsByProtocol

NetPeers

StateAccountKey

StateActorCodeCIDs

StateGetActor

StateLookupID

StateMarketStorageDeal

StateMinerAvailableBalance

StateMinerDeadlines

StateMinerInfo

StateMinerPartitions

StateMinerPower

StateMinerProvingDeadline

StateNetworkName

StateNetworkVersion

StateReadState -> "not implemented"

StateVerifiedClientStatus

SyncState

Version
- Return
  - venus:
  ```
   type Version struct {
   	Version string
   
   	// APIVersion is a binary encoded semver version of the remote implementing
   	// this api
   	//
   	APIVersion api.Version
   }
  ```
  > {"jsonrpc":"2.0","result":{"Version":"1.6.0+git.53a13524","APIVersion":66816},"id":0}
  - lotus:
  ```
   type APIVersion struct {
   	Version string
   
   	// APIVersion is a binary encoded semver version of the remote implementing
   	// this api
   	//
   	// See APIVersion in build/version.go
   	APIVersion Version
   
   	// TODO: git commit / os / genesis cid?
   
   	// Seconds
   	BlockDelay uint64
   }
  ```

WalletBalance 

WalletList -> WalletAddresses

## Lotus miner
这一块在venus中使用了新的实现`venus-cluster`，其设计理念与 `lotus-miner` 不同，暂时先考虑仅显示其自身实现的指标。下列API请求所实现的指标后续讨论实现方案，比如：`farcaster` 列出所需数据，由`venus-cluster`提供API或直接实现指标。

ActorAddress

SealingSchedDiag

SectorsList

SectorsStatus

StorageInfo

StorageList

StorageLocal

StorageStat

Version

WorkerJobs

WorkerStats

## Lotus markets/boost  -> venus-market

这里部分接口的权限是 `admin`, 需要对应权限的 `token`

DealsConsiderOfflineRetrievalDeals

DealsConsiderOfflineStorageDeals

DealsConsiderOnlineRetrievalDeals

DealsConsiderOnlineStorageDeals

`venus-market` 可以为多个矿工提供服务，而 `lotus-market` 仅为一个矿工服务，故下列接口多了 `minerID` 参数。

MarketGetAsk
- lotus: MarketGetAsk(ctx context.Context) (*storagemarket.SignedStorageAsk, error) 
- venus: MarketGetAsk(ctx context.Context, mAddr address.Address) (*storagemarket.SignedStorageAsk, error) 

MarketGetRetrievalAsk
- lotus: MarketGetRetrievalAsk(ctx context.Context) (*retrievalmarket.Ask, error) 
- venus: MarketGetRetrievalAsk(ctx context.Context, mAddr address.Address) (*retrievalmarket.Ask, error) 

MarketListDataTransfers

NetBandwidthStats -> "not implemented"

NetBandwidthStatsByProtocol -> "not implemented"

NetPeers - > "not implemented"

标注 "not implemented" 会在近期实现。

**Comment by s0nik42** [comment]
> StateReadState -> "not implemented"

We use StateReadState to retrieve lock funds : "PreCommitDeposits", "LockedFunds", "FeeDebt", "InitialPledge"
do you have another call to retrieve these information  ?

> It will probably be easier if Farcaster get the numbers from metrics instead of APIs for venus-cluster.
How does farcaster can access the metrics ? can you give an example ?

**Comment by Fatman13** [comment]
> We use StateReadState to retrieve lock funds : "PreCommitDeposits", "LockedFunds", "FeeDebt", "InitialPledge"
do you have another call to retrieve these information ?

@diwufeiwen ，这个有办法吗？

> How does farcaster can access the metrics ? can you give an example ?

@diwufeiwen ，cluster是不是还没有开始做？要等我们做好再有example还是说，跟venus-miner之类的差不多？

**Comment by Fatman13** [comment]
Hello, @s0nik42, glad that you asked!

> We use StateReadState to retrieve lock funds : "PreCommitDeposits", "LockedFunds", "FeeDebt", "InitialPledge"
do you have another call to retrieve these information ?

It is the team's goal to have StateReadState implemented in either the next sprint or the sprint after next one. 

> How does farcaster can access the metrics ? can you give an example ?

The metrics of venus-cluster is still under development. Meanwhile if there is any metrics you wish to see, please feel free to let us know.

For examples, we can have the chain service on Calib updated with latest version of venus-miner and venus-messager (with metrics implemented) and expose relevant Prometheus ports to you for your testing.

**Comment by Fatman13** [comment]
关联：
- [ ] https://github.com/filecoin-project/venus/issues/5181

**Comment by diwufeiwen** [comment]
`StateReadState` has been implemented

**Comment by s0nik42** [comment]
scoping the integration effort now. Will let you know soon

**Comment by s0nik42** [comment]
Coud you give me  access to : 
- a venus-market API 
- a prometheus containing metrics for venus-cluster would be great if you have an example some document of the data exposed this way. 

Feedback on Venus daemon API : 
1. The version on calibnet is `1.6.0+git.cda4771b` and doesn't seems to have StateReadState implemented
2. I cannot use WalletAddresses : 

```
curl -s -X PST -H Authorization: Bearer XXX --data { "jsonrpc": "2.0", "method": "Filecoin.WalletAddresses", "params": [[]], "id": 3 }+  http://XXX:XXX/rpc/v0
jq .
{
  "jsonrpc": "2.0",
  "id": 3,
  "error": {
    "code": -32602,
    "message": "wrong param count (method 'Filecoin.WalletAddresses'): 1 != 0"
  }
}
```

All other API calls works fine 👍🏻

**Comment by Fatman13** [comment]
@s0nik42, glad you asked! 

> a venus-market API

I will see if @venus-ops has deployed venus-market on calib. Will come back to you on this.

> a prometheus containing metrics for venus-cluster would be great if you have an example some document of the data exposed this way.

Yes, venus-cluster comes with a default exporter too. But current [documentation](https://github.com/ipfs-force-community/venus-cluster/blob/main/docs/zh/14.venus-sector-manager%E7%9A%84mertics%E4%BD%BF%E7%94%A8.md) hasn't been translated yet. Maybe google translate could give you a quick overview? 

> Feedback on Venus daemon API :

Will bring this up with @venus-ops too on Slack.

**Comment by Fatman13** [comment]
One other thing, the engineering team has been giving thoughts on how Venus systems could give feedbacks to a monitoring system like Farcaster. So the team think that maybe instead of the monitoring system actively pulling APIs, maybe another approach could be Venus itself feed the data to Farcaster. This would lower the risk of API pulling affecting essential PoST messages to go through. 

Would love to hear your thoughts on that.

**Comment by diwufeiwen** [comment]
> WalletAddresses

Hi, WalletAddresses API:  "params": []  eg:
curl http://127.0.0.1:3453/rpc/v1 -X POST -H "Content-Type: application/json"  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.5Jiv1JbwgipQF1UhBwx0F0Bv5soGsw3zYE9mAhXSN40"  -d '{"method": "Filecoin.WalletAddresses","params":[], "id": 0}'
{"jsonrpc":"2.0","result":["t3wy7qwnramiy2bfna2fpx66o5i23zojpn465xj5jmp6f7lyfpaqt3ycfi2sa2sl343bpr6ctcg6qgttlqwwiq"],"id":0}

StateReadState need version greater than  v1.7.1
curl http://192.168.200.151:3453/rpc/v1 -X POST -H "Content-Type: application/json" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibGl0YW8iLCJwZXJtIjoic2lnbiIsImV4dCI6IiJ9.y2FL4Zmwe3ucZzNYoSktyhuha32BIhHJdeIcEWcwkEo"  -d '{"method": "Filecoin.StateReadState","params":["t010938",[{"/":"bafy2bzacedaxuyqh62jvnlup2wmawmcweorkje5izwauy7kimjvllyrietpxe"},{"/":"bafy2bzacecipapqwrxfuzq3q43a5jet2gjkp2cgrxd2dr5p6mjw3f2blza54a"}]], "id": 0}'
{"jsonrpc":"2.0","result":{"Balance":"204512070952769073821452","Code":{"/":"bafk2bzacea6rabflc7kpwr6y4lzcqsnuahr4zblyq3rhzrrsfceeiw2lufrb4"},"State":{"Info":{"/":"bafy2bzacedqyguguuz2y7xfopwyzjebmafgfvn2fu3eboextqgi4wr55e54ma"},"PreCommitDeposits":"0","LockedFunds":"157470841343073168935340","VestingFunds":{"/":"bafy2bzacebfu5ff7gupz7ffqoll527ol4v6q3c2maeilfgkwijz52kl5ow7eg"},"FeeDebt":"0","InitialPledge":"4437784873001587235025","PreCommittedSectors":{"/":"bafy2bzaceamp42wmmgr2g2ymg46euououzfyck7szknvfacqscohrvaikwfay"},"PreCommittedSectorsCleanUp":{"/":"bafy2bzaceaa2jny7gkgdwnid4kuldau6bnvgyss5bszo4uy6uikrncvdu5mc2"},"AllocatedSectors":{"/":"bafy2bzaceb43qhhv4v27hi26ylneaqcgi2ijtipubjhu5aolc7swqcp7m7ccg"},"Sectors":{"/":"bafy2bzaceb5rulsmcc3zqwjug6zkyugnnz2o7tq36llkkubpfvp2at3slnpbw"},"ProvingPeriodStart":1278969,"CurrentDeadline":1,"Deadlines":{"/":"bafy2bzaceb6prd2g3vizdwveilr7cspbdgy7zli77xq37x3ti4vuvrpyphzo2"},"EarlyTerminations":[0],"DeadlineCronActive":true}},"id":0}

**Comment by s0nik42** [comment]
> One other thing, the engineering team has been giving thoughts on how Venus systems could give feedbacks to a monitoring system like Farcaster. So the team think that maybe instead of the monitoring system actively pulling APIs, maybe another approach could be Venus itself feed the data to Farcaster. This would lower the risk of API pulling affecting essential PoST messages to go through.
> 
> Would love to hear your thoughts on that.

I fully agree on that, I did ask that to the lotus when starting developing Farcaster, scraping the API every minutes is definitely not the best approach but that's the only solution available now (for lotus).

 What farcaster is doing right now is retrieving all the data over the REST API , formatting and enriching the data then exposing them to prometheus.

The best approach would probably be to transition and have most of the data enriched directly available in prometheus.

**Comment by s0nik42** [comment]
I think we must define the right target and path. As if it diverged to much from lotus, building a different implementation might be more relevant.

**Comment by Fatman13** [comment]
> The best approach would probably be to transition and have most of the data enriched directly available in prometheus.

yes, if you see any metrics that is lacking, please feel free to let the team know! Venus is more than happy to give the metrics that users want.

> I think we must define the right target and path. As if it diverged to much from lotus, building a different implementation might be more relevant.

yes, there could be new path that more tailored toward Venus. The devs suggested that to take advantage of Venus’ distributed design and maybe have one layout for chain service operator and another layout for SP as the idea of chain service is that multiple SP could share access to one chain service and what a chain service operator may want to see is different from what a SP may want to see on their dashboards.

**Comment by Fatman13** [comment]
Hello, @s0nik42! If you are stuck on any API usage of Venus node or design choices, please feel free to let us know!

**Comment by Fatman13** [comment]
Closing the planning thread and moving the conversation to https://github.com/filecoin-project/venus/issues/5357
