### ISSUE TITLE
Sprint 46

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5162]
## 背景

sprint日期：08/08 - 08/19
Github Project：[面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)
代码审阅：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)
代码检查项：[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)
文档建立：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)
组件发版：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5125)

## 目标

- [ ] 推进`venus`与生态项目集成
  - [ ] https://github.com/filecoin-project/venus/issues/5156
- [x] PR提交测试用例规范（已完成：60%-70%）
- [ ] Q3Q4研发目标 https://github.com/filecoin-project/venus/discussions/5062
- [ ] STM
  - [x] https://github.com/filecoin-project/venus/issues/5116
  - [ ] https://github.com/filecoin-project/venus/issues/5158
  - [x] https://github.com/filecoin-project/venus/issues/5159
- [ ] 需求整理流程文档，PR至[devguidance](https://github.com/ipfs-force-community/dev-guidances)
- [ ] `venus-market`重构代码设计和方案讨论。（已完成：80%） 
  - [ ] 地址账号及相关逻辑draft版本，publish订单聚合方式，fundmgr资产聚合方式 聚合方式使用地址和账号
- [ ] https://github.com/filecoin-project/venus/issues/5121
- [ ] 分支开发/发版规范[升级](https://github.com/filecoin-project/venus/blob/master/documentation/misc/release-issue-template.md)
- [ ] [venus-mienr核心代码(project-root/mine)package,单元测试, 期望覆盖率能达到为50%-60% ](https://github.com/filecoin-project/venus-miner/pull/122) [覆盖率66%]
- [x] 推动在tinygo中支持wasm32-unknown-unknown的target， 首先第一步完成proposal编写，并争取到tinygo维护人员的支持。https://github.com/ipfs-force-community/go-fvm-sdk/issues/55
- [ ] https://github.com/filecoin-project/venus/issues/5163
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/362 grant申请？
- [x] #5167
- [ ] venus-cluster
  - [x] 扇区重建能力
  - [x] 实现可扩展的数据库mongo （测试中）
 - [ ] issue 精细化管理（形成文档）：约定以下情形的处理流程(初期可以制定简单粗暴的规则：比如谁提的谁去做，或者提的人认为应该和谁一起解决，要是说不出来就自己解决；其他...)
    - [ ] 已经被assign但是长期（超过两个sprint？）没结果的如何处理（https://github.com/filecoin-project/venus/issues/5008）
    - [ ] 提了长期没人接的如何处理（https://github.com/filecoin-project/venus/issues/5024）
    - [ ] 提交issue必要的约定：不重复提交，必要的描述，自己认为有意义的见解等 ... ...
