### ISSUE TITLE
[探索] `Sealing-as-a-Service`看看`Venus`如何能在里面做一些贡献

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5163]
相关讨论：
- [ ] https://github.com/filecoin-project/lotus/discussions/9079

关联`cluster`:
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/368

前期参与的好处：
- [ ] 参与早期API的设计
- [ ] 便于融入当前`venus-cluster`的架构
- [ ] 探索新的业务形态
- [ ] grant机会

**Comment by Fatman13** [comment]
新的业务形态：
![image](https://user-images.githubusercontent.com/1591330/183033857-e22a0f66-5a53-4b6f-a5c2-2da29268d74f.png)

**Comment by Fatman13** [comment]
关联：
- [ ] https://github.com/filecoin-project/venus/discussions/5198
