### ISSUE TITLE
[venus] splitstore自动截链，自动prune?

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5182]
### 链服务模块 / Chain Service Components

- [X] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

是否可以考虑增加chainsplit相关的自动截链的功能？自动prune？

相关：
- [ ] https://github.com/filecoin-project/lotus/pull/9123

**Comment by Fatman13** [comment]
@cloudxin ，觉得这种功能意义大吗？

**Comment by cloudxin** [comment]
是有这个需求，可以减少人工运维成本

**Comment by chenjihu** [comment]
如果这个功能的目的是做同步链数据修剪，我觉得很有意义。现在每隔一段时间就得重新制作snapshot，然后清空daemon目录中的chain数据，再重新导入。 工作量不大，但是很烦。

**Comment by Fatman13** [comment]
splitStore v2 [文档](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/393)要出了。

**Comment by Fatman13** [comment]
splitStore v2 正式版[文档](https://lotus.filecoin.io/lotus/manage/chain-management/#splitstore)。

**Comment by Fatman13** [comment]
Don Kabat，以前参加过孵化器的同学，挺关注这个问题的。

关联：
- [ ] Slack[讨论](https://filecoinproject.slack.com/archives/CPFTWMY7N/p1663711329434859)

**Comment by Fatman13** [comment]
社区有2个人反应过，splitstore定期做压缩的时候，会影响节点服务器的性能，导致出块失败。可能需要慎重考虑？

**Comment by hunjixin** [comment]
磁盘消耗太大了

**Comment by Fatman13** [comment]
看看[splitstore V2](https://lotus.filecoin.io/lotus/manage/chain-management/#splitstore)是否解决了内存spike的问题？

CC @cloudxin @hunjixin

**Comment by Fatman13** [comment]
和fevm相关的一个升级：
- [ ] https://github.com/filecoin-project/lotus/pull/9960

**Comment by Fatman13** [comment]
deadlock：
- [ ] https://github.com/filecoin-project/lotus/pull/9903

**Comment by Fatman13** [comment]
Lotus在持续修复slpitstore中：
- [ ] https://github.com/filecoin-project/lotus/pull/10332

**Comment by Fatman13** [comment]
新动向：
- [ ] https://github.com/filecoin-project/lotus/pull/10429

**Comment by Fatman13** [comment]
- [ ] https://github.com/filecoin-project/lotus/pull/10391

**Comment by Fatman13** [comment]
- [ ] https://github.com/filecoin-project/lotus/pull/10387

**Comment by Fatman13** [comment]
- [ ] https://github.com/filecoin-project/lotus/pull/10366

**Comment by Fatman13** [comment]
新关联：
- [ ] https://github.com/filecoin-project/lotus/pull/10505

**Comment by Fatman13** [comment]
关联：
- [ ] https://github.com/filecoin-project/lotus/pull/10621

**Comment by Fatman13** [comment]
这个 Q 的季度目标。CC @simlecode

**Comment by simlecode** [comment]
这个 Q 会整理和设计，不会开始写代码

**Comment by Fatman13** [comment]
我先把这个老 issue 给关了。

**Comment by Fatman13** [comment]
- [ ] https://github.com/filecoin-project/lotus/pull/11269

**Comment by Fatman13** [comment]
- [ ] https://github.com/filecoin-project/lotus/pull/11349
