### ISSUE TITLE
Sprint 47

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5205]
## 背景

sprint日期：08/22 - 09/02
Github Project：[面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)
代码审阅：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)
代码检查项：[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)
文档建立：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)
组件发版：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5162)

## 目标

- [ ] 推进`venus`与生态项目集成
  - [ ] https://github.com/filecoin-project/venus/issues/5156
  - [x] https://github.com/filecoin-project/venus/issues/5181
- [x] STM
  - [x] https://github.com/filecoin-project/venus/issues/5158
- [ ] ‼️ 链服务和订单服务版本发布 (待测试)
  - [ ] https://github.com/filecoin-project/venus/issues/5121
  - [ ] https://github.com/filecoin-project/venus/issues/5204
  - [ ] 分支开发/发版规范[升级](https://github.com/filecoin-project/venus/blob/master/documentation/misc/release-issue-template.md) (@simlecode实践测试[PR](https://github.com/filecoin-project/venus/pull/5171)）
- [x] 重构venus链服务用户、矿工、签名者体系（完成了第一轮的review及测试，还有兼容旧版本的方面需要支持及测试：https://github.com/filecoin-project/venus/discussions/5231）
  - [x] venus-messager 消息推送重构
  - [x] venus-market 升级引用的venus组件
  - [x] 相关文档更新
  - [x] 全流程测试 
  - [ ] 兼容旧版本，平滑升级
- [x] venus-market增加监控指标 https://github.com/filecoin-project/venus/issues/5207
- [x] https://github.com/filecoin-project/venus/issues/5108
- [ ] venus-mienr核心代码(project-root/mine)package,单元测试, 期望[覆盖率能达到为50%-60% ](https://github.com/filecoin-project/venus-miner/pull/122) [覆盖率66%]（80%）
- [ ] PM
  - [x] ‼️ sealing as a service，venus-cluster适应性文档，潜在的大项目（优先级较高） 
  - [x] 需求整理流程文档，PR至[devguidance](https://github.com/ipfs-force-community/dev-guidances)
  - [ ] ~~Q3Q4研发目标 https://github.com/filecoin-project/venus/discussions/5062~~
 - [ ] venus-cluster
   - [ ] 完成 v0.5.0 的主体功能开发，确定包含的功能边界
   - [ ] 完善 v0.5.0 引入的新特性相关的文档
- [x] #5209
- [ ]  go-fvm-sdk. issue解决
  - [ ] https://github.com/ipfs-force-community/go-fvm-sdk/issues/68
  - [ ] https://github.com/ipfs-force-community/go-fvm-sdk/issues/69
  - [ ] https://github.com/ipfs-force-community/go-fvm-sdk/issues/34
  - [ ] https://github.com/ipfs-force-community/go-fvm-sdk/issues/43
- [ ] 社区与产品需求（待评估）
   - [ ] https://github.com/filecoin-project/venus/issues?q=is%3Aissue+is%3Aopen+label%3AC-triage

## 外部的需求管理

来自外部的需求目前都提在issues里，处理相对滞后，应该有一套可执行的流程管理起来：比如以sprint为单位，上个sprint提出的本sprint进行处理（这个处理不一定是要完成），处理结果有两类：接受则转为正常的issues，按优先级及耗费时间等选择本sprint完成或者以后完成；不接受加commit关闭。

## 简易社区与产品需求`issue`流程

- 社区或者pm创建`issue`，先由@fatman13添加`C-triage`标签
- 每次Sprint总结会，由一位大神会前过一遍`C-triage`的[issue列表](https://github.com/filecoin-project/venus/issues?q=is%3Aissue+is%3Aopen+label%3AC-triage)
- 根据这位大神的评估，会上对每个`issue`决定做还是不做，做的话就去掉`C-triage`标签。可选：并打上优先级标签？

**Comment by diwufeiwen** [comment]
- [  ] https://github.com/filecoin-project/venus/issues/5208
