### ISSUE TITLE
Sprint 48

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5257]
## 背景

Sprint日期：09/05 - 09/16
Github Project：[面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)
> 代码审阅：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)，代码检查项：[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)，文档建立：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)，组件发版：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)，需求流程：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E4%BA%A7%E5%93%81%E9%9C%80%E6%B1%82%E7%AE%A1%E7%90%86.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5205)

## 主题

- [x] 代码质量提升（STM推进/评估，CI集成，单元测试）
- [x] 企业级客户测试
- [x] account体系重构
- [x] 生态项目合作farcaster进一步沟通/共识

## ‼️高优先级

- [ ] v1.7.0 bug修复
- [x] https://github.com/filecoin-project/venus/issues/5008
- [x] https://github.com/filecoin-project/venus/issues/5139
- [x] https://github.com/filecoin-project/venus/issues/5274

### 项目&生态

- [ ] 进一步完善`sprint`制度
- [x] fil-singapore产品等准备
- [ ] https://github.com/filecoin-project/venus/discussions/5062
- [ ] https://github.com/filecoin-project/venus/issues/5156
- [ ] 回复[待评估](https://github.com/orgs/filecoin-project/projects/51/views/12)任务 

### 链服务

- [ ] `venus-mienr`核心代码(project-root/mine)package,单元测试, 期望[覆盖率能达到为50%-60% ](https://github.com/filecoin-project/venus-miner/pull/122)（review中）
- [x] 重构venus链服务用户、矿工、签名者体系（完成review commits修改与升级测试，达到可以合并到master分支的程度：https://github.com/filecoin-project/venus/discussions/5231）
  - [x] 兼容旧版本，平滑升级
  - [x] 相关组件可合并到master（主要工作是处理review commits；rebase代码，解决冲突，特别是venus-messager的测试用例）
  
#### metrics 指标
- [x] 整理已实现的指标，形成文档
- [ ] 开discussion向社区征集关心的指标（这个也许征集不到）
- [ ] 将我们指标设计理念形成文档与farcast沟通
  - [ ] 我们的指标想分成链服务指标（给服务商使用）和 SP指标（给实际做算力的用户使用），这点与lotus不同，也许可以作为申请Grant的一个特色；
  - [ ] 我们实现的指标同步给farcast，之前说venus-market部分仍然以API方式提供，这部分要编写文档并同步
#### STM推进
- [ ] 添加stm ci https://github.com/filecoin-project/venus/issues/5220（2个方案，看情况增加；另外看STM有没有方案）
- [x]  venus-messenger添加stm 注解https://github.com/filecoin-project/venus/issues/5273
### 订单服务
- [ ] https://github.com/filecoin-project/venus/issues/5235 （review中）
- [x] https://github.com/filecoin-project/venus/issues/5263

### 算力服务
- [ ] venus-cluster 扇区重建 bug 修复 (ipfs-force-community/venus-cluster#362)
- [x] venus-worker add_piece 优化 (ipfs-force-community/venus-cluster#415)
- [x] venus-sector-manager 扩展可用数据库类型 (ipfs-force-community/venus-cluster#323)
- [x] venus-cluster 日志精简 (ipfs-force-community/venus-cluster#252, ipfs-force-community/venus-cluster#404)

### FVM

- [ ] https://github.com/ipfs-force-community/go-fvm-sdk/issues/34 （review中）
