### ISSUE TITLE
[venus] nv17 代码待合并

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#5287]
### 链服务模块 / Chain Service Components

- [X] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

- [x] https://github.com/filecoin-project/lotus/pull/9342
- [x] https://github.com/filecoin-project/venus/issues/5338
- [x] https://github.com/filecoin-project/lotus/pull/9348
- [ ] https://github.com/filecoin-project/venus/issues/5334
- [x] https://github.com/filecoin-project/lotus/pull/9440
- [x] https://github.com/filecoin-project/venus/issues/5347
- [x] https://github.com/filecoin-project/lotus/pull/9462
- [x] https://github.com/filecoin-project/lotus/pull/9476
- [x] https://github.com/filecoin-project/lotus/pull/9437
- [x] https://github.com/filecoin-project/lotus/pull/9412
- [x] https://github.com/filecoin-project/lotus/pull/9450
- [x] https://github.com/filecoin-project/lotus/pull/9483
- [x] https://github.com/filecoin-project/lotus/pull/9485
- [x] https://github.com/filecoin-project/lotus/pull/9454
- [x] https://github.com/filecoin-project/lotus/pull/9502
- [x] https://github.com/filecoin-project/lotus/pull/9518
- [x] https://github.com/filecoin-project/lotus/pull/9520
- [x] https://github.com/filecoin-project/lotus/pull/9525
- [x] https://github.com/filecoin-project/lotus/pull/9570
- [x] https://github.com/filecoin-project/lotus/pull/9577
- [x] https://github.com/filecoin-project/lotus/pull/9585
- [x] https://github.com/filecoin-project/lotus/pull/9584
- [x] https://github.com/filecoin-project/lotus/pull/9586
- [x] https://github.com/filecoin-project/lotus/pull/9591
- [x] https://github.com/filecoin-project/lotus/pull/9603
- [x] https://github.com/filecoin-project/lotus/pull/9640

待评估（不太确定）：
- [x] https://github.com/filecoin-project/lotus/pull/9546
- [x] https://github.com/filecoin-project/lotus/pull/9545 (可能只要等最新版本的state type？)
- [x] https://github.com/filecoin-project/lotus/pull/9537 （同上）
- [ ] https://github.com/filecoin-project/lotus/pull/9624

**Comment by Fatman13** [comment]
下面这个需要吗？好像他们标注了nv17需要。

待评估PR：
- [ ] https://github.com/filecoin-project/lotus/pull/9484

**Comment by simlecode** [comment]
要的

**Comment by Fatman13** [comment]
[lotus-rc3](https://github.com/filecoin-project/lotus/releases/tag/v1.18.0-rc3) 发布。CC @simlecode @hunjixin

**Comment by Fatman13** [comment]
@simlecode 这个迁移测试是不是咱们不需要？

- [ ] https://github.com/filecoin-project/lotus/pull/9549

**Comment by simlecode** [comment]
> @simlecode 这个迁移测试是不是咱们不需要？
> 
> * [ ]  [test: nv17 migration lotus#9549](https://github.com/filecoin-project/lotus/pull/9549)

不用

**Comment by simlecode** [comment]
venus正式版本已发布，主要代码已完成合并
