### ISSUE TITLE
Sprint 49

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5296]
## 背景

Sprint日期：09/19 - 09/30
Github Project：[Venus面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[Cluster面板](https://github.com/orgs/ipfs-force-community/projects/5)
> Github Project：[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)，代码审阅：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)，代码检查项：[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)，文档建立：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)，组件发版：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)，需求流程：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E4%BA%A7%E5%93%81%E9%9C%80%E6%B1%82%E7%AE%A1%E7%90%86.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5257)

## 主题

- [ ] 代码质量提升（STM推进/评估，CI集成，单元测试）
- [ ] 企业级客户上线一个集群（验证，迁移，定义+-差值）
- [ ] 合并 lotus 1.17.* 代码，为nv17的升级做准备 
- [x] 梳理[Q4目标](https://github.com/filecoin-project/venus/discussions/5062)
- [ ] cluster发版

## ‼️重要维护

- [x] https://github.com/filecoin-project/venus/issues/5282
- [ ] [force任务](https://github.com/orgs/filecoin-project/projects/51/views/13)列表 🐢 `持续`
- [ ] [待评估](https://github.com/orgs/filecoin-project/projects/51/views/12)任务列表（评估后移除`C-triage`，并添加优先级label）🐢 `持续`
- [ ] https://github.com/filecoin-project/venus/issues/5281 🐢 `持续`
- [ ] 上个sprint PR review，合并至master
- [ ] 测试流程梳理（打label？环境？）

### 项目&生态

- [x] https://github.com/filecoin-project/venus/discussions/5062 🐢 `持续`
- [ ] https://github.com/filecoin-project/venus/issues/5156 🐢 `持续`
- [ ] #5303 🐢 `持续`

### 链服务

- [x] `venus-mienr`核心代码(project-root/mine)package单元[测试](https://github.com/filecoin-project/venus-miner/pull/122) ⚠️ `review中`
- [ ] 重构venus链服务用户、矿工、签名者[体系](https://github.com/filecoin-project/venus/discussions/5231) ⚠️ `review中`

#### metrics 指标
- [ ] 与farcaster达成一致，10月前能有个接入venus api可演示的daemon
- [x] 把孵化器升级到1.7.*版本，实现指标的组件开放接口给farcaster测试
- [ ] 整理已实现的指标，形成[文档](https://github.com/filecoin-project/venus/issues/4951#issuecomment-1249058210)，给到farcaster（参考[cluster](https://github.com/ipfs-force-community/venus-cluster/blob/main/docs/zh/14.venus-sector-manager%E7%9A%84mertics%E4%BD%BF%E7%94%A8.md)）
  - [x] venus-miner
  - [x] venus-messager
  - [ ] venus-gateway
  - [x] venus-market
  - [x] venus-cluster 

#### STM推进
- [ ] 添加[STM CI](https://github.com/filecoin-project/venus/issues/5220) (完成至少确定方案)
- [x] #5306
- [x] #5316

### 订单服务
- [x] https://github.com/filecoin-project/venus/issues/5235 ⚠️ `review中`

### 算力服务

- [x] ‼️ 优先保证发版相关问题
- [ ] venus-cluster 扇区重建 bug 修复 (ipfs-force-community/venus-cluster#362) (完成 95%)
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/424 (review 中)
- [x] ~~发布 0.4.0 正式版~~ (不准备发0.4.0正式版，直接发0.5.0正式版)
- [ ] 发布 0.5.0 RC 版本（核心功能: 扇区重建，扩展可用数据库类型）(完成 90%)
- [x] worker list 命令的输出结果增加 plan 列 (ipfs-force-community/venus-cluster#428)
- [ ] VSM能否完善proving check --slow 功能？(ipfs-force-community/venus-cluster#430) (review 中)
- [x] ~~完成扇区时最多可以同时传输N个扇区的配置 (ipfs-force-community/venus-cluster#427)~~(意义不大, 不考虑实现)

### FVM
- [x] https://github.com/ipfs-force-community/go-fvm-sdk/issues/34 ⚠️ `review中`
- [ ] https://github.com/ipfs-force-community/go-fvm-sdk/issues/75

## 其他issue

- [ ] venus API & cmd & 简单优化
  - [x] https://github.com/filecoin-project/venus/issues/5297
  - [x] https://github.com/filecoin-project/venus/issues/5294
  - [x] https://github.com/filecoin-project/venus/issues/5252
  - [x] https://github.com/filecoin-project/venus/issues/5243
  - [x] https://github.com/filecoin-project/venus/issues/5242
  - [x] https://github.com/filecoin-project/venus/issues/5244
  - [x] https://github.com/filecoin-project/venus/issues/5222
  - [x] https://github.com/filecoin-project/venus/issues/5221
  - [x] https://github.com/filecoin-project/venus/issues/5219
  - [x] https://github.com/filecoin-project/venus/issues/5119
  - [x] https://github.com/filecoin-project/venus/issues/5094
- [x] https://github.com/filecoin-project/venus/issues/5277
- [x] https://github.com/filecoin-project/venus/issues/5229
- [x] https://github.com/filecoin-project/venus/issues/5160
- [x] https://github.com/filecoin-project/venus/issues/5312
