### ISSUE TITLE
[ssm] ssm development / ssm 组件开发（前venus-tool）

### ISSUE THREAD

**Issue by hunjixin** [filecoin-project/venus#5304]
### 链服务模块 / Chain Service Components

- [ ] venus
- [ ] venus-auth
- [ ] venus-gateway
- [ ] venus-messager
- [ ] venus-miner
- [ ] 文档 / docs

### 订单服务模块 / Deal Service Components

- [ ] venus-market
- [ ] 文档 / docs

### 算力服务模块 / Storage Power Service Components

- [ ] venus-sector-manager
- [ ] venus-worker
- [ ] 文档 / docs

### 描述 / Description

目的:

1. 在云组件环境下，由于私钥和节点是分离的，有些涉及到资金方面操作客户不太方便执行，需要捣腾私钥，不安全。
2. 有的操作需要动用owner私钥 例如提取资金，改变owner， 这种操作最好是客户自行操作，不和云组建打交道
3. 有的功能对于节点来说是可选的，例如多签/paychnnel这种功能，这种功能可以分离到工具中实现
4. venus一些需要用户在本地进行的操作，未来考虑用户可以本地执行一些操作。
       * 用户可以自行查看messager中他发送的消息状态， 需改变授权并加入用户级别的检查
       * market中矿工自行设置peerid/addr/asks,自行决定是否加入market中心市场。订单状态信息，变化订单状态等。 需改变授权并加入用户级别的检查
       * 王麟提到过的的签名记录查询

本issue用于收集相关的需求及issue，再有类似的issue请关联到本issue，并标记成重复并关闭

功能点：
- [x] 发送,查询消息
- [x] 创建矿工
- [x] 改变owner/worker/control地址
- [x] replace操作
- [x] 提取资产
- [x] 改变/审批受益人
- [x] 抵押/提取 market资产
- [x] 多签相关命令
- [ ] 离线WalletSign操作
- [ ] paychannel相关命令（使用的少

- [x] 云服务签名审计
- [x] 签名记录查询

可以考虑使用的技术
- [ ] 脚本式可交互命令行
- [ ] 增加UI界面
- [ ] 消息及执行结果存储在本地，提供查看导出的功能
- [ ] 本地数据库可采用badger本地存储或者sqlite
- [ ] 需要提供mpool接入和replace的能力
- [ ] 是否消息需要接入messager， 目前考虑有的消息适合推送到messager（续期之类的），有的敏感消息不适合推送到messager

**Comment by Fatman13** [comment]
关联：
- [ ] https://github.com/filecoin-project/lotus/pull/9322

**Comment by Fatman13** [comment]
Lotus的一些想法借鉴？

```
lotus-shed export --tipset=@1234
```

关联PR：
- [ ] https://github.com/filecoin-project/lotus/pull/9434

**Comment by Fatman13** [comment]
fplus相关：
- [ ] https://github.com/filecoin-project/lotus/pull/9468

**Comment by Fatman13** [comment]
Louts shed 测试 migration 用？

- [ ] https://github.com/filecoin-project/lotus/pull/9547

**Comment by Fatman13** [comment]
lotus-shed另外一个工具：
- [ ] https://github.com/filecoin-project/lotus/pull/9590

**Comment by Fatman13** [comment]
另外gas预估工具，看上去不错？
- [ ] https://github.com/filecoin-project/lotus/pull/9654

**Comment by Fatman13** [comment]
另外一个功能：
- [ ] https://github.com/filecoin-project/lotus/pull/9738

**Comment by Fatman13** [comment]
shed另外一个功能：
- [ ] https://github.com/filecoin-project/lotus/pull/9737

**Comment by Fatman13** [comment]
另外一个功能：
- [ ] https://github.com/filecoin-project/lotus/pull/9845

**Comment by Fatman13** [comment]
可能的一个util？

- [ ] https://github.com/filecoin-project/lotus/pull/10032

**Comment by Fatman13** [comment]
venus-cluster可能可以迁移过来的命令？

- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/579
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/547
