### ISSUE TITLE
Sprint 50

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5332]
## 背景

Sprint日期：10/08 - 10/21
Github Project：[Venus面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[Cluster面板](https://github.com/orgs/ipfs-force-community/projects/5)，[fvm面板](https://github.com/orgs/ipfs-force-community/projects/7/views/1)
> Github Project：[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)，代码审阅：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)，代码检查项：[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)，文档建立：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)，组件发版：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)，需求流程：[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E4%BA%A7%E5%93%81%E9%9C%80%E6%B1%82%E7%AE%A1%E7%90%86.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5296)

## 主题

- [ ] 代码质量提升（STM等）
- [ ] [NV17](https://github.com/filecoin-project/community/discussions/74?sort=top#discussioncomment-3825422)网络升级
- [ ] fvm [milestone](https://github.com/filecoin-project/devgrants/issues/672)攻坚

## ‼️重要维护

- [ ] `Venus`项目任务维护
  - [ ] [force任务](https://github.com/orgs/filecoin-project/projects/51/views/13)列表 🐢 `持续` 
  - [ ] 连服务/订单服务[待评估](https://github.com/orgs/filecoin-project/projects/51/views/12)任务列表（评估后移除`C-triage`，并添加优先级label）🐢 `持续`
  - [ ] Cluster[待评估](https://github.com/orgs/ipfs-force-community/projects/5/views/18)任务列表（评估后移除`C-triage`，并添加优先级label）🐢 `持续`
- [ ] https://github.com/filecoin-project/venus/issues/5281 🐢 `持续`
- [x] https://github.com/filecoin-project/venus/issues/5311 🐢 `持续`
- [ ] https://github.com/filecoin-project/venus/issues/5287 🐢 `持续`
- [x] ‼️兼容NV17版本发布
  - [x] https://github.com/filecoin-project/venus/issues/5350 
  - [x] https://github.com/filecoin-project/venus/issues/5351
  - [x] https://github.com/ipfs-force-community/venus-cluster/issues/465

### 项目&生态

- [x] https://github.com/filecoin-project/venus/discussions/5062 🐢 `持续`
- [ ] https://github.com/filecoin-project/venus/issues/5156 🐢 `持续`
- [ ] FIP相关
  - [ ] #5303 🐢 `持续`(解读文档完成了50%)
  - [ ] https://github.com/ipfs-force-community/venus-cluster/issues/464
  - [x] https://github.com/filecoin-project/venus/issues/5349

### 链服务

- [ ] 重构venus链服务用户、矿工、签名者[体系](https://github.com/filecoin-project/venus/discussions/5231) ⚠️ `review中` (nv17之后)
- [ ] #5346（待Lotus合并）
- [x] ‼️Network v17 Shark cali网络发版
- [x] https://github.com/filecoin-project/venus/issues/5349

#### metrics 指标（[milestone](https://github.com/filecoin-project/devgrants/issues/858)）

- [ ] 持续推进与`farcaster`的合作 🐢 `持续`
- [ ] 整理已实现的指标，形成[文档](https://github.com/filecoin-project/venus/issues/4951#issuecomment-1249058210)，给到farcaster（参考[cluster](https://github.com/ipfs-force-community/venus-cluster/blob/main/docs/zh/14.venus-sector-manager%E7%9A%84mertics%E4%BD%BF%E7%94%A8.md)）
  - [ ] venus-gateway

#### STM推进

- [ ] 添加[STM CI](https://github.com/filecoin-project/venus/issues/5220) (使用circleci作为测试信息详情方案)(完成度:0/8)
- [ ] #5385
- [ ] venus-miner 完善**必要的**测试用例,添加STM注解
- [ ] venus-market 完善**必要的**测试用例, 添加STM注解

### 订单服务

- [ ] https://github.com/filecoin-project/venus/issues/5345

### 算力服务

- [x] venus-cluster 扇区重建 bug 修复 (ipfs-force-community/venus-cluster#362) 
- [x] https://github.com/ipfs-force-community/venus-cluster/issues/424 
- [x] 发布 0.5.0 RC 版本（核心功能: 扇区重建，扩展可用数据库类型）
- [x] VSM能否完善proving check --slow 功能？(ipfs-force-community/venus-cluster#430) 
- [x] 收集企业级运维人员对cluster的意见， 满足一些迫切的需求。目前看cluster可能需要5.0才行。
- [x] 扇区重建文档编写
- [x] v0.5.0 持续 bug 修复
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/443

### FVM（[milestone](https://github.com/filecoin-project/devgrants/issues/672)）

- [ ] https://github.com/ipfs-force-community/go-fvm-sdk/issues/75
- [x] https://github.com/ipfs-force-community/go-fvm-sdk/issues/78

## 其他`issue`
- [x] https://github.com/filecoin-project/venus/issues/5283
- [x] https://github.com/filecoin-project/venus/issues/5331
- [ ] https://github.com/filecoin-project/venus/issues/5190（nv17后）

**Comment by Fatman13** [comment]
关联：
- [ ] https://github.com/filecoin-project/venus/discussions/5352
