### ISSUE TITLE
[Collab] Preliminary testing and feature requests (with Farcaster)

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5357]
## Background

This issue is to track anything that may become a problem during testing Venus metrics system on Calibration network and feature requests that might come along from such tests.

## Calib Env

- [x] Setup [Calib](https://filecoinproject.slack.com/archives/CEHHJNJS3/p1662438043841369) env

## Related

- [x] Previous planning thread: https://github.com/filecoin-project/venus/issues/5156
- [ ] Discussion on new metrics for storage power service: https://github.com/ipfs-force-community/venus-cluster/issues/473

**Comment by Fatman13** [comment]
Additional feature request from @Julien:

- the sealing activity :
  - List of sectors in the sealing pipeline with all the relevant information : (state(PC1/PC2/AP/etc...) , worker running the task, duration in that state, deals included in the sector, etc ...
  - Workers stats : ressource available and use, current jobs
- The full sector list :
  - current states
  - timestamps

**Comment by Fatman13** [comment]
最近和 @julien 交流之后，可能farcaster这一块维护将不多了。之后着眼于 [CIDgravity](https://github.com/filecoin-project/venus/issues/5565) 的集成。
