### ISSUE TITLE
Sprint 51

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5406]
## 背景

Sprint日期：10/24 - 11/04
Github Project：[Venus面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[Cluster面板](https://github.com/orgs/ipfs-force-community/projects/5)，[fvm面板](https://github.com/orgs/ipfs-force-community/projects/7/views/1)
> Github Project[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)，代码审阅[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)，代码检查项[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)，文档建立[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)，组件发版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)，需求流程[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E4%BA%A7%E5%93%81%E9%9C%80%E6%B1%82%E7%AE%A1%E7%90%86.md)，设计模版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3%E6%A8%A1%E7%89%88.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5332)

## 主题

- [ ] 代码质量提升（STM等）
- [ ] [NV17](https://github.com/filecoin-project/community/discussions/74?sort=top#discussioncomment-3825422)网络发布正式版本
- [x] 新market定位设计初步共识
- [x] FVM wallaby集成

## ‼️重要维护
- [ ] 需求池（点击对应标签，选取`issue`）
  - [ ] https://github.com/filecoin-project/venus/labels/P1 需求（点击标签查看列表） 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/P2 需求（点击标签查看列表） 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/P3 需求（点击标签查看列表） 🐢 `持续`
- [ ] `Venus`项目任务维护 
  - [ ] https://github.com/filecoin-project/venus/labels/CU-force-community [force任务](https://github.com/orgs/filecoin-project/projects/51/views/13)列表 🐢 `持续` 
  - [ ] 链服务/订单服务[待评估](https://github.com/orgs/filecoin-project/projects/51/views/12)任务列表（评估后移除 https://github.com/filecoin-project/venus/labels/C-triage ，并添加优先级label）🐢 `持续`
  - [ ] 算力服务`cluster`[待评估](https://github.com/orgs/ipfs-force-community/projects/5/views/18)任务列表（评估后移除 https://github.com/filecoin-project/venus/labels/C-triage ，并添加优先级label）🐢 `持续`
  - [ ] 给需要测试的`issue`打上 https://github.com/filecoin-project/venus/labels/C-need-testing
  - [ ] https://github.com/filecoin-project/venus/discussions/4847?sort=new 🐢 `持续`
- [ ] NV17发布相关
  - [ ] https://github.com/filecoin-project/venus/issues/5402
  - [ ] https://github.com/filecoin-project/venus/issues/5401
  - [ ] https://github.com/ipfs-force-community/venus-cluster/issues/488 
  - [ ] https://github.com/filecoin-project/venus/issues/5287 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/discussions/5386

### 项目&生态

- [x] FIP相关
  - [x] https://github.com/ipfs-force-community/venus-cluster/issues/464

### 链服务

- [ ] 重构venus链服务用户、矿工、签名者[体系](https://github.com/filecoin-project/venus/discussions/5231) ⚠️ `review中` (nv17之后) 🐢 `持续`
- [ ] #5346（待Lotus合并）blocked

#### metrics 指标（[milestone](https://github.com/filecoin-project/devgrants/issues/858)）

- [x] 整理已实现的指标，形成[文档](https://github.com/filecoin-project/venus/issues/4951#issuecomment-1249058210)，给到farcaster（参考[cluster](https://github.com/ipfs-force-community/venus-cluster/blob/main/docs/zh/14.venus-sector-manager%E7%9A%84mertics%E4%BD%BF%E7%94%A8.md)）

#### STM推进

- [ ] 添加[STM CI](https://github.com/filecoin-project/venus/issues/5220) (使用circleci作为测试信息详情方案)(完成度:1/7, [venus-miner])

### 订单服务

- [x] https://github.com/filecoin-project/venus/issues/5345
- [x] [多用户设计文档/架构重新设计？](https://github.com/filecoin-project/venus/issues/5410)

### 算力服务

- [x] 多机 wdpost 内部实现 (测试中)
- [ ] 外部执行器改造内部实现 (50%)
- [x] nv17 测试
- [ ] ~~https://github.com/ipfs-force-community/venus-cluster/issues/443~~ 优先级比较低，先搁置

### FVM（[milestone](https://github.com/filecoin-project/devgrants/issues/672)）

- [x] https://github.com/ipfs-force-community/go-fvm-sdk/issues/75

## 其他`issue`

- [ ] https://github.com/filecoin-project/venus/issues/5190 （nv17后）
- [x] #5409
- [ ] https://github.com/filecoin-project/venus/issues/5403
- [x] https://github.com/filecoin-project/venus/issues/5370
- [ ] https://github.com/filecoin-project/venus/issues/5429

**Comment by Fatman13** [comment]
review：
- [ ] 设计文档模版 https://github.com/ipfs-force-community/dev-guidances/pull/43
