### ISSUE TITLE
Sprint 52

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5449]
## 背景

Sprint日期：11/07 - 11/18
Github Project：[Venus面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[Cluster面板](https://github.com/orgs/ipfs-force-community/projects/5)，[fvm面板](https://github.com/orgs/ipfs-force-community/projects/7/views/1)
> Github Project[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)，代码审阅[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)，代码检查项[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)，文档建立[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)，组件发版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)，需求流程[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E4%BA%A7%E5%93%81%E9%9C%80%E6%B1%82%E7%AE%A1%E7%90%86.md)，设计模版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3%E6%A8%A1%E7%89%88.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5406)

## 主题

- [ ] 代码质量提升（STM等）
- [x] [NV17](https://github.com/filecoin-project/community/discussions/74?sort=top#discussioncomment-3825422)网络发布正式版本
- [ ] 新`market`多sp支持 Or 统一运行模式？（开发分支）
- [x] 新`account`体系开发分支合并

## ‼️重要维护
- [ ] 需求池（点击对应标签，选取`issue`）🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/P1 需求（点击标签查看列表） 
  - [ ] https://github.com/filecoin-project/venus/labels/P2 需求（点击标签查看列表） 
  - [ ] https://github.com/filecoin-project/venus/labels/P3 需求（点击标签查看列表） 
  - [ ] https://github.com/filecoin-project/venus/labels/C-Blocked 的`issue`检查是否可以继续执行？
- [ ] `Venus`项目任务维护 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/CU-force-community force任务列表 
  - [ ] 链服务/订单服务待评估 https://github.com/filecoin-project/venus/labels/C-triage 任务列表（评估后移除 https://github.com/filecoin-project/venus/labels/C-triage ，并添加优先级label）
  - [ ] 算力服务`cluster`[待评估](https://github.com/orgs/ipfs-force-community/projects/5/views/18)任务列表（评估后移除 https://github.com/filecoin-project/venus/labels/C-triage ，并添加优先级label）
  - [ ] 给需要测试的`issue`打上 https://github.com/filecoin-project/venus/labels/C-need-testing
  - [ ] https://github.com/filecoin-project/venus/discussions/4847?sort=new 
- [ ] 设计进行中 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus-docs/pull/353 
  - [ ] https://github.com/filecoin-project/venus-docs/pull/352 
  - [ ] https://github.com/filecoin-project/venus-docs/pull/351 
  - [ ] https://github.com/filecoin-project/venus-docs/pull/346 
- [ ] NV17发布相关
  - [x] https://github.com/filecoin-project/venus/issues/5402
  - [x] https://github.com/filecoin-project/venus/issues/5401
  - [ ] https://github.com/ipfs-force-community/venus-cluster/issues/488 
  - [x] https://github.com/filecoin-project/venus/issues/5287 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/discussions/5386

### 项目&生态

- [ ] https://github.com/filecoin-project/venus/discussions/5420
- [ ] https://github.com/filecoin-project/venus/discussions/5452 ( @Joss-Hua )

### 链服务

- [ ] account[体系](https://github.com/filecoin-project/venus/discussions/5231) 合并至一个开发分支 🐢 `持续`

#### metrics 指标（[milestone](https://github.com/filecoin-project/devgrants/issues/858)）

- [ ] 推进milestone
- [ ] 推进企业运维使用 

#### STM推进

- [x] 添加[STM CI](https://github.com/filecoin-project/venus/issues/5220) (使用circleci作为测试信息详情方案)(完成度:7/8, [venus-miner, venus, venus-gateway, venus-auth, venus-wallet, venus-messenger])

### 订单服务

- [ ] https://github.com/filecoin-project/venus/issues/5410 ([market改造](https://github.com/filecoin-project/venus/issues/5453)计划第一步)

### 算力服务

- [x] 多机 `wdpost` 内部实现 (测试中)
- [ ] 外部执行器改造 [venus-cluster#530](https://github.com/ipfs-force-community/venus-cluster/pull/530)

### FVM（[milestone](https://github.com/filecoin-project/devgrants/issues/672)）

- [ ] https://github.com/ipfs-force-community/go-fvm-sdk/issues/75
- [x] https://github.com/ipfs-force-community/go-fvm-sdk/issues/87

## 其他`issue`

- [x] https://github.com/filecoin-project/venus/issues/5190 （nv17后）
- [x] https://github.com/filecoin-project/venus/issues/5403
- [x] https://github.com/filecoin-project/venus/issues/5429
- [x] https://github.com/filecoin-project/venus/issues/5344
- [x] https://github.com/filecoin-project/venus/issues/5197
- [ ] https://github.com/filecoin-project/venus/issues/5115
- [ ] https://github.com/filecoin-project/venus/issues/5021
- [x] https://github.com/filecoin-project/venus/issues/5359

## 讨论

- 开发流程中遇到的任何问题和困难？

**Comment by Fatman13** [comment]
关联：
- [ ] https://github.com/filecoin-project/venus/discussions/5420

**Comment by Fatman13** [comment]
讨论：
- [ ] https://github.com/filecoin-project/venus/discussions/5468

changelog流程；

**Comment by Fatman13** [comment]
社区测试反馈：
2. 目前提测的版本无法给出准确的测试范围，测试每次几乎都需要全面回归测试，降低了测试效率
3. 更新文档中缺少本次对比上次版本改动的信息，很容易造成大多数的改动仅有开发知道，信息同步存在问题

**Comment by Fatman13** [comment]
--repo文件名不一样，home文件名不一样。

**Comment by Fatman13** [comment]
可执行包位置 cluster: /dist/bin 位置不统一。

**Comment by Fatman13** [comment]
issue: 换掉centOS

**Comment by Fatman13** [comment]
研发，测试流程需另外专门会议。

**Comment by Fatman13** [comment]
下个sprint主题，团队目标。
