### ISSUE TITLE
Sprint 53

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5483]
## 背景

Sprint日期：11/21 - 12/02
Github Project：[Venus面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[Cluster面板](https://github.com/orgs/ipfs-force-community/projects/5)，[fvm面板](https://github.com/orgs/ipfs-force-community/projects/7/views/1)
> Github Project[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)，代码审阅[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)，代码检查项[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)，文档建立[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)，组件发版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)，需求流程[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E4%BA%A7%E5%93%81%E9%9C%80%E6%B1%82%E7%AE%A1%E7%90%86.md)，设计模版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3%E6%A8%A1%E7%89%88.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5406)

## 主题

- [x] 新`market`多sp支持（review @simlecode @hunjixin）
- [x] https://github.com/filecoin-project/venus/discussions/5482 设计讨论
- [ ] 数据隔离 https://github.com/filecoin-project/venus/issues/5384
- [x] market启动模式统一([market改造](https://github.com/filecoin-project/venus/issues/5453)计划第二步)

## ‼️重要维护
- [ ] 需求池（点击对应标签，选取`issue`）🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/P1 需求, https://github.com/filecoin-project/venus/labels/P2 需求, https://github.com/filecoin-project/venus/labels/P3 需求（点击标签查看列表） 
  - [ ] https://github.com/filecoin-project/venus/labels/C-Blocked 的`issue`检查是否可以继续执行？
- [ ] `Venus`项目任务维护 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/CU-force-community force任务列表
  - [ ] 链服务/订单服务待评估 https://github.com/filecoin-project/venus/labels/C-triage 任务列表，算力服务[待评估](https://github.com/orgs/ipfs-force-community/projects/5/views/18)任务列表
  - [ ] 给需要测试的`issue`打上 https://github.com/filecoin-project/venus/labels/C-need-testing
  - [ ] https://github.com/filecoin-project/venus/discussions/4847?sort=new 
- [ ] 设计进行中 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus-docs/pull/353 
  - [ ] https://github.com/filecoin-project/venus-docs/pull/346 
  - [x] https://github.com/filecoin-project/venus/discussions/5482 （潜在grant机会？）
- [x] NV17发布相关
  - [x] https://github.com/filecoin-project/venus/discussions/5386
- [ ] 团队 
  - [ ] 双数`sprint`对团队目标进行review  

### 项目&生态

- [ ] https://github.com/filecoin-project/venus/discussions/5420
- [ ] https://github.com/filecoin-project/venus/discussions/5468
- [ ] https://github.com/filecoin-project/venus/discussions/5452 ( @Joss-Hua )

#### metrics 指标（[milestone](https://github.com/filecoin-project/devgrants/issues/858)）

- [x] https://github.com/filecoin-project/venus/issues/5487

### 订单服务

- [x] https://github.com/filecoin-project/venus/issues/5410 ([market改造](https://github.com/filecoin-project/venus/issues/5453)计划第一步)
- [x] https://github.com/filecoin-project/venus/issues/5493
- [x] https://github.com/filecoin-project/venus/issues/5021
- [x] https://github.com/filecoin-project/venus/issues/5498

### 算力服务

- [x] 多机 `wdpost` 内部实现
- [ ] https://github.com/ipfs-force-community/venus-cluster/pull/530
- [x] 其他 issue 处理（https://github.com/ipfs-force-community/venus-cluster/issues/535）

### FVM（[milestone](https://github.com/filecoin-project/devgrants/issues/672)）

- [x] https://github.com/ipfs-force-community/go-fvm-sdk/issues/105
- [x] https://github.com/ipfs-force-community/go-fvm-sdk/issues/96
- [ ] https://github.com/ipfs-force-community/go-fvm-sdk/issues/75

## 其他`issue`

- [x] https://github.com/filecoin-project/venus/issues/5115
- [x] https://github.com/filecoin-project/venus/issues/5492
- [x] https://github.com/filecoin-project/venus/issues/5486
- [x] https://github.com/filecoin-project/venus/issues/5367

### venus-tool

- [x] 讨论，拉会 by tanlang

## 讨论

- 开发流程中遇到的任何问题和困难？🐢 `持续`
- 与社区测试流程更好输出功能和测试范围流程讨论
- 上期sprint总结会遗留`issue`
  - issue：--repo文件名不一样，home文件名不一样。by duowen
  - issue: 可执行包位置 cluster: /dist/bin 位置不统一。by duowen
  - issue: 换掉centOS by duowen

**Comment by Fatman13** [comment]
- [ ] Lotus scaling讨论 https://github.com/filecoin-project/lotus/discussions/9686

**Comment by Fatman13** [comment]
- [ ] 看看 splitstore v2 https://github.com/filecoin-project/venus/issues/5182

**Comment by Fatman13** [comment]
测试流程待在讨论。
