### ISSUE TITLE
Sprint 55

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5580]
## Background / 背景

Sprint date / Sprint日期：12/19 - 12/30
Github Project：[Venus面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[Cluster面板](https://github.com/orgs/ipfs-force-community/projects/5)，[fvm面板](https://github.com/orgs/ipfs-force-community/projects/7/views/1)
Product release / 版本发布：[计划](https://github.com/filecoin-project/venus/discussions/5468)
> Github Project[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)，代码审阅[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)，代码检查项[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)，文档建立[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)，组件发版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)，需求流程[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E4%BA%A7%E5%93%81%E9%9C%80%E6%B1%82%E7%AE%A1%E7%90%86.md)，设计模版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3%E6%A8%A1%E7%89%88.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5527)

## Theme / 主题

- [ ] venus-tool 第一阶段的开发（待code review）
- [x] 23年团队目标讨论
- [ ] https://github.com/filecoin-project/venus/issues/5550
- [x] venus企业级用户协助

## ‼️ Maintenance / 重要维护
- [ ] 需求池（点击对应标签，选取`issue`）🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/P1 需求, https://github.com/filecoin-project/venus/labels/P2 需求, https://github.com/filecoin-project/venus/labels/P3 需求（点击标签查看列表） 
  - [ ] https://github.com/filecoin-project/venus/labels/C-Blocked 的`issue`检查是否可以继续执行？
- [ ] `Venus`项目任务维护 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/CU-force-community force任务列表
  - [ ] 链服务/订单服务待评估 https://github.com/filecoin-project/venus/labels/C-triage 任务列表，算力服务[待评估](https://github.com/orgs/ipfs-force-community/projects/5/views/18)任务列表
  - [ ] 给需要测试的`issue`打上 https://github.com/filecoin-project/venus/labels/C-need-testing
  - [ ] https://github.com/filecoin-project/venus/discussions/4847?sort=new 
- [ ] 设计进行中 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus-docs/pull/353 
  - [ ] https://github.com/filecoin-project/venus-docs/pull/346 
- [ ] 团队 
  - [ ] 双数`sprint`对团队目标进行review  

### Project & Ecosystem / 项目&生态

- [ ] #5581
- [x] https://github.com/filecoin-project/venus/issues/5582
- [ ] https://github.com/filecoin-project/venus/issues/5583

### Chain Service / 链服务

- [ ] https://github.com/filecoin-project/venus/issues/5558
### Storage Deal Service / 订单服务

- [ ] https://github.com/filecoin-project/venus/issues/5484
- [x] https://github.com/filecoin-project/venus/issues/5565
- [ ] https://github.com/filecoin-project/venus/issues/5569

### Storage Power Service / 算力服务

- [ ] https://github.com/ipfs-force-community/venus-cluster/pull/530

### FVM（[milestone](https://github.com/filecoin-project/devgrants/issues/672)）

- [ ] https://github.com/ipfs-force-community/go-fvm-sdk/issues/75

### ssm (storage-service-manager)（前venus-tool） 

- [x] 数据隔离 https://github.com/filecoin-project/venus/issues/5384 (review中)
- [x] https://github.com/filecoin-project/venus/issues/5510 (review中)
- [x] 实现消息查看 (review中)
- [x] 实现修改消息发送的地址参数的功能 (review中)
- [x] 实现 replace 消息的功能  (review中)
- [x] 实现订单管理   (review中)
- [x] 实现矿工相关信息查询  (review中)

## Others / 其他`issue`

- [x] https://github.com/filecoin-project/venus/issues/5466
- [x] https://github.com/filecoin-project/venus/issues/5544
- [x] https://github.com/filecoin-project/venus/issues/5546

## Discussion / 讨论

- 开发流程，社区测试流程中遇到的任何问题和困难？🐢 `持续`

**Comment by Fatman13** [comment]
给社区测试开一个私有的repo提issue？

**Comment by Fatman13** [comment]
snapUp算法优化提上议程？

**Comment by Fatman13** [comment]
三个产品版本发布是否能够岔开？

**Comment by Fatman13** [comment]
计划从需求出发，突破各自的覆盖范围。制定优先级。优先级更高的安排更多人员，去学习，去pickup。

一个成员阶段性专攻某个模块。大循环可以更多讨论计划，小循环专攻。

**Comment by Fatman13** [comment]
cli，目录，配置，数据库
