### ISSUE TITLE
Sprint 56

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5625]
## Background / 背景

Sprint date / Sprint日期：01/03 - 01/18
Github Project：[Venus面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[Cluster面板](https://github.com/orgs/ipfs-force-community/projects/5)，[fvm面板](https://github.com/orgs/ipfs-force-community/projects/7/views/1)
Product release / 版本发布：[计划](https://github.com/filecoin-project/venus/discussions/5468)
> Github Project[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)，代码审阅[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)，代码检查项[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)，文档建立[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)，组件发版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)，需求流程[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E4%BA%A7%E5%93%81%E9%9C%80%E6%B1%82%E7%AE%A1%E7%90%86.md)，设计模版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3%E6%A8%A1%E7%89%88.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5580)

## Theme / 主题

- [ ] venus-tool 第一阶段的开发（待code review）
- [ ] https://github.com/filecoin-project/venus/issues/5550
- [ ] nv18版本准备/发布（lotus nv18[时间线](https://github.com/filecoin-project/community/discussions/74)，venus nv18[时间线](https://github.com/filecoin-project/venus/discussions/5649)）
  - [ ] https://github.com/filecoin-project/venus/issues/5651
  - [ ] https://github.com/filecoin-project/venus/issues/5650
- [ ] 智子产品化方案初稿

## ‼️ Maintenance / 重要维护
- [ ] 需求池（点击对应标签，选取`issue`）🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/P1 需求, https://github.com/filecoin-project/venus/labels/P2 需求, https://github.com/filecoin-project/venus/labels/P3 需求（点击标签查看列表） 
  - [ ] https://github.com/filecoin-project/venus/labels/C-Blocked 的`issue`检查是否可以继续执行？
- [ ] `Venus`项目任务维护 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/CU-force-community force任务列表
  - [ ] 链服务/订单服务待评估 https://github.com/filecoin-project/venus/labels/C-triage 任务列表，算力服务[待评估](https://github.com/orgs/ipfs-force-community/projects/5/views/18)任务列表
  - [ ] 给需要测试的`issue`打上 https://github.com/filecoin-project/venus/labels/C-need-testing
  - [ ] https://github.com/filecoin-project/venus/discussions/4847?sort=new 
- [ ] 设计进行中 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus-docs/pull/353 
  - [ ] https://github.com/filecoin-project/venus-docs/pull/346 
- [ ] 团队 
  - [ ] 双数`sprint`对团队目标进行review  

### Project & Ecosystem / 项目&生态

- [ ] #5581
- [ ] #5583
- [x] #5624

### Chain Service / 链服务

- [x] https://github.com/filecoin-project/venus/issues/5627
- [x] https://github.com/filecoin-project/venus/issues/5558
- [x] https://github.com/filecoin-project/venus/issues/5612
- [ ] https://github.com/filecoin-project/venus/issues/5533

### Storage Deal Service / 订单服务

- [ ] https://github.com/filecoin-project/venus/issues/5484 （场景细化）
- [ ] https://github.com/filecoin-project/venus/issues/5569

### Storage Power Service / 算力服务

- [x] https://github.com/ipfs-force-community/venus-cluster/issues/561 (代码review)
- [x] 内部 mysql 支持
- [x] https://github.com/ipfs-force-community/venus-cluster/issues/559
- [x] https://github.com/ipfs-force-community/venus-cluster/issues/552
- [x] https://github.com/ipfs-force-community/venus-cluster/issues/543
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/532 (reviewing)
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/422 (lotus的过于繁杂,cluster目前的也许偏简单,一些信息没有显示,需要更多使用者反馈,再优化)
- [x] https://github.com/ipfs-force-community/venus-cluster/issues/421
- [x] https://github.com/ipfs-force-community/venus-cluster/issues/562
- [x] https://github.com/ipfs-force-community/venus-cluster/issues/384
- [x] https://github.com/ipfs-force-community/venus-cluster/issues/412

### FVM（[milestone](https://github.com/filecoin-project/devgrants/issues/672)）

- [ ] https://github.com/ipfs-force-community/go-fvm-sdk/issues/75

### ssm (storage-service-manager)（前venus-tool） 

- [x] 代码review
- [x] [支持修改owner/worker/control地址](https://github.com/filecoin-project/venus/issues/5638)
- [x] [支持修改受益人](https://github.com/filecoin-project/venus/issues/5642)
- [x] [资产管理相关命令](https://github.com/filecoin-project/venus/issues/5653)
- [ ] 多签地址相关命令
   - [x] 完善 venus 多签地址相关类型和接口
   - [x]  创建多签地址
   - [x] 增加签名者
   - [x] 减少参与者
   - [x] 替换参与者
   - [x] 发起提案
   - [x] 查看提案
   - [x] 取消提案
   - [x] 赞成提案

## Discussion / 讨论

- 开发流程，社区测试流程中遇到的任何问题和困难？🐢 `持续`

**Comment by Fatman13** [comment]
cli，目录，配置，数据库

**Comment by Fatman13** [comment]
nv18合并代码继续跟进；社区测试尽量测试主流程；环境变量，默认值，细节，社区测试提前参与；

**Comment by Fatman13** [comment]
spriint计划会流程改进。

**Comment by Fatman13** [comment]
放弃gitlab，统一github？这样不用tb，可以直接统一用github？

**Comment by Fatman13** [comment]
品牌重塑，repo是否需要重命名？重命名工作量？
