### ISSUE TITLE
Sprint 58

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5706]
## Background / 背景

Sprint date / Sprint日期：02/13 - 02/24
Github Project：[Venus面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[Cluster面板](https://github.com/orgs/ipfs-force-community/projects/5)，[fvm面板](https://github.com/orgs/ipfs-force-community/projects/7/views/1)
Product release / 版本发布：[计划](https://github.com/filecoin-project/venus/discussions/5468)
> Github Project[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)，代码审阅[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)，代码检查项[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)，文档建立[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)，组件发版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)，需求流程[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E4%BA%A7%E5%93%81%E9%9C%80%E6%B1%82%E7%AE%A1%E7%90%86.md)，设计模版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3%E6%A8%A1%E7%89%88.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5670)

## Theme / 主题

- [x] https://github.com/filecoin-project/venus/issues/5550
- [ ] nv18版本准备/发布（lotus nv18[时间线](https://github.com/filecoin-project/lotus/discussions/10219#discussion-4838517)，venus nv18[时间线](https://github.com/filecoin-project/venus/discussions/5649)）
  - [x] https://github.com/filecoin-project/venus/issues/5651
  - [x] https://github.com/filecoin-project/venus/issues/5650
  - [x] https://github.com/ipfs-force-community/venus-cluster/issues/581
- [x] grant checkin 验收
- [ ] venus 系统测试

## ‼️ Maintenance / 重要维护
- [ ] 需求池（点击对应标签，选取`issue`）🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/P1 需求, https://github.com/filecoin-project/venus/labels/P2 需求, https://github.com/filecoin-project/venus/labels/P3 需求（点击标签查看列表） 
  - [ ] https://github.com/filecoin-project/venus/labels/C-Blocked 的`issue`检查是否可以继续执行？
- [ ] `Venus`项目任务维护 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/CU-force-community force任务列表
  - [ ] 链服务/订单服务待评估 https://github.com/filecoin-project/venus/labels/C-triage 任务列表，算力服务[待评估](https://github.com/orgs/ipfs-force-community/projects/5/views/18)任务列表
  - [ ] 给需要测试的`issue`打上 https://github.com/filecoin-project/venus/labels/C-need-testing
  - [ ] https://github.com/filecoin-project/venus/discussions/4847?sort=new 
- [ ] 设计进行中 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus-docs/pull/353 
  - [ ] https://github.com/filecoin-project/venus-docs/pull/346 
- [ ] 团队 
  - [ ] 双数`sprint`对团队目标进行review  

### Project & Ecosystem / 项目&生态

- [x] 推进各类集群 v1.9.0 venus-market 升级完成
- [ ] #5581 （试行中...）
- [ ] https://github.com/filecoin-project/venus/issues/5669
- [ ] #5715
- [ ] 生态分享 by xiaosheng

### Chain Service / 链服务

- [ ] https://github.com/filecoin-project/venus/issues/5672
- [x] https://github.com/ipfs-force-community/venus-cluster/issues/581
- [x] #5718

#### metrics 指标（[milestone](https://github.com/filecoin-project/devgrants/issues/858)）

- [ ] #5716

### Storage Deal Service / 订单服务

- [ ] https://github.com/filecoin-project/venus/issues/5484 （Reviewing）
- [ ] https://github.com/filecoin-project/venus/issues/5569

### Storage Power Service / 算力服务

- [x] https://github.com/ipfs-force-community/venus-cluster/issues/595
~~- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/489~~ https://github.com/ipfs-force-community/venus-cluster/issues/604
- [x] https://github.com/ipfs-force-community/venus-cluster/issues/581
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/443
- [ ] [venus-cluster退回lotus-miner工具链完善](https://github.com/ipfs-force-community/venus-cluster/issues/625)
  - [x] 扇区MetaData导出
  - [ ] 扇区永久存储导出
  - [x] next sid 更新
  - [x] 操作手册
  - [x] 扇区MetaData导入
- [x] add-pieces 全局并发限制

### Storage Service Manager
- [ ] venus-wallet 实现对签名记录的查询 (review 中)
- [ ] venus-tool 增加签名审计的相关功能  (review 中)
- [ ] venus-tool 第二阶段开发的细节确定

### FVM（[milestone](https://github.com/filecoin-project/devgrants/issues/672)）

- [ ] #5717

## Discussion / 讨论

- 开发流程，社区测试流程中遇到的任何问题和困难？🐢 `持续`

**Comment by Fatman13** [comment]
1.11 版本 market v2.7 趁修改仓库名称时迁回？venus仍然留在filecoin-project下面？

**Comment by Fatman13** [comment]
extend claim terms 加入 market-client 里面？

**Comment by Fatman13** [comment]
repo 迁移，github 组织？确认

**Comment by Fatman13** [comment]
market 优化
