### ISSUE TITLE
[调研] RIBS

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5746]
blockStore新的升级版本？解决很多规模化的问题。

关联：
- [ ] https://filecoinproject.slack.com/archives/C027TQMUVJN/p1676883217835909
- [ ] https://github.com/lotus-web3/ribs/
- [ ] https://www.youtube.com/watch?v=fgloFGa7-Ps 

![image](https://user-images.githubusercontent.com/1591330/220514297-b48ea7d4-01ec-4901-aad6-495953006359.png)
