### ISSUE TITLE
Sprint 59

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5758]
## Background / 背景

Sprint date / Sprint日期：02/27 - 03/10
Github Project：[Venus面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[Cluster面板](https://github.com/orgs/ipfs-force-community/projects/5)，[fvm面板](https://github.com/orgs/ipfs-force-community/projects/7/views/1)
Product release / 版本发布：[计划](https://github.com/filecoin-project/venus/discussions/5468)
> Github Project[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)，代码审阅[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)，代码检查项[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)，文档建立[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)，组件发版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)，需求流程[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E4%BA%A7%E5%93%81%E9%9C%80%E6%B1%82%E7%AE%A1%E7%90%86.md)，设计模版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3%E6%A8%A1%E7%89%88.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5706)

## Theme / 主题

- [x] nv18版本准备/发布（lotus nv18[时间线](https://github.com/filecoin-project/lotus/discussions/10219#discussion-4838517)，venus nv18[时间线](https://github.com/filecoin-project/venus/discussions/5649)）
  - [x] https://github.com/filecoin-project/venus/issues/5764 
  - [x] https://github.com/filecoin-project/venus/issues/5765
  - [x] https://github.com/ipfs-force-community/venus-cluster/issues/635
- [ ] venus 系统测试探索
- [ ] market 优化（需求收集）
- [ ] repo 迁移讨论

## ‼️ Maintenance / 重要维护
- [ ] 需求池（点击对应标签，选取`issue`）🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/P1 需求, https://github.com/filecoin-project/venus/labels/P2 需求, https://github.com/filecoin-project/venus/labels/P3 需求（点击标签查看列表） 
  - [ ] https://github.com/filecoin-project/venus/labels/C-Blocked 的`issue`检查是否可以继续执行？
- [ ] `Venus`项目任务维护 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/CU-force-community force任务列表
  - [ ] 链服务/订单服务待评估 https://github.com/filecoin-project/venus/labels/C-triage 任务列表，算力服务[待评估](https://github.com/orgs/ipfs-force-community/projects/5/views/18)任务列表
  - [ ] 给需要测试的`issue`打上 https://github.com/filecoin-project/venus/labels/C-need-testing
  - [ ] https://github.com/filecoin-project/venus/discussions/4847?sort=new 
- [ ] 设计进行中 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus-docs/pull/353 
  - [ ] https://github.com/filecoin-project/venus-docs/pull/346 
- [ ] 团队 
  - [ ] 双数`sprint`对团队目标进行review  

### Project & Ecosystem / 项目&生态

- [ ] #5581 （试行中...）
- [ ] https://github.com/filecoin-project/venus/issues/5669
- [x] #5760

### Chain Service / 链服务

- [ ] https://github.com/filecoin-project/venus/issues/5672
- [x] https://github.com/filecoin-project/venus/issues/5756
- [x] https://github.com/filecoin-project/venus/issues/5734
- [ ] https://github.com/filecoin-project/venus/issues/5732

### Storage Deal Service / 订单服务

- [ ] https://github.com/filecoin-project/venus/issues/5484 （Reviewing）
- [x] https://github.com/filecoin-project/venus/issues/5569
- [ ] #5759

### Storage Power Service / 算力服务

- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/443
- [ ] [venus-cluster退回lotus-miner工具链完善](https://github.com/ipfs-force-community/venus-cluster/issues/625)
  - [ ] 扇区永久存储导出
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/328
### Storage Service Manager
- [x] https://github.com/filecoin-project/venus/issues/5725
- [x] https://github.com/filecoin-project/venus/issues/5806
- [x] venus-tool 第二阶段开发的细节确定 (https://github.com/filecoin-project/venus/issues/5803)

## Others / 其他`issue`

- [x] 合并 v1.11 的开发分支

## Discussion / 讨论

- 开发流程，社区测试流程中遇到的任何问题和困难？🐢 `持续`

**Comment by Fatman13** [comment]
其他产品规划。

**Comment by Dio7777777** [comment]
目前issue的一些现况：
- 总量：        目前在no sprint中issue的数量为78个
- 时间分布： 30个左右是年前的issue
- 状态：        21个是done的但是no sprint，其中大部分是最近1个迭代的issue
- 优先级：    57个issue中优先级分布： P0 0个、P1 1个、P2 20个 、P3 13个、无优先级23个

**Comment by Fatman13** [comment]
团队目标准备

**Comment by Fatman13** [comment]
spliteStore 自动剪裁，是否重启？

**Comment by Fatman13** [comment]
版本主题突出，优先级讨论，milestone主题。

**Comment by Fatman13** [comment]
面板上体现工作进度？

**Comment by Fatman13** [comment]
分享使用公司repo？
