### ISSUE TITLE
[venus-project] repo migration planning / repo 迁移计划

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5760]
## 背景

- [ ] https://github.com/filecoin-project/venus/discussions/5420

借着 venus 品牌重塑，以及 nv18 与 nv19 发版中间的机会，把所有 repo 彻底重新梳理/规划。

## 时间线

- sprint 59 讨论决定迁移计划
- 在这个 [nv19 milestone](https://github.com/filecoin-project/venus/milestone/54) 之前，完成迁移

## 规划

具体规划参见[下方](https://github.com/filecoin-project/venus/issues/5760#issuecomment-1445559242)。 欢迎参与讨论。

## 其他关联

- [x] https://github.com/filecoin-project/venus/issues/5528
- [ ] https://github.com/filecoin-project/venus/issues/5529

**Comment by Fatman13** [comment]
cc @hunjixin review req

**Comment by hunjixin** [comment]
@Fatman13 麻烦按如下格式列出：

| repo      |  repo name | data home repo name |
| ----------- | ----------- | ----------- |
| venus-market       | venus-market       | . droplet |
| venuswallet      | ？       | .venus_wallet -> .venus-wallet|

原来的链服务名称不用变吗。

**Comment by Fatman13** [comment]
| repo before     |  repo after | CLI | data home repo name |
| ----------- | ----------- | ----------- | ----------- |
| filecoin-project/venus-market       |  /ipfs-force-community/droplet  |  droplet, droplet-client  | . droplet |
|  /ipfs-force-community/venus-cluster   |   /ipfs-force-community/damocles  |  damocles-manager, damocles-worker  | . damocles |

wallet 和其他链服务组件，感觉名字可以保留？@hunjixin 你觉得呢？

**Comment by simlecode** [comment]
调整repo path：https://github.com/filecoin-project/venus/issues/5528

**Comment by hunjixin** [comment]
本来也是要改的了

**Comment by hunjixin** [comment]
🤔这样venus就一点体现不到了

**Comment by hunjixin** [comment]
https://github.com/filecoin-project/venus/issues/5529

**Comment by LinZexiao** [comment]
miner, messager, auth 作为名称主体, 挺简单直观的

**Comment by Fatman13** [comment]
sophon-messager, sophon-auth, sophon-auth

**Comment by Fatman13** [comment]
规划结束。

**Comment by hunjixin** [comment]
编译输出位置统一。 dist目录？

**Comment by Fatman13** [comment]
> 编译输出位置统一。 dist目录？

可以，学习下 venus-cluster 的做法。

**Comment by 0x5459** [comment]
分支名称统一？
master -> main

See: https://github.com/github/renaming#why-main

**Comment by LinZexiao** [comment]
> 分支名称统一？ master -> main
> 
> See: https://github.com/github/renaming#why-main

支持, 纯粹因为名字更短了一些, 另外 master/slave 这种命名习惯确实不讨喜

**Comment by elvin-du** [comment]
amgr，bmgr，mmgr，三个缩写的含义什么？和哪些repo对应？

**Comment by Fatman13** [comment]
> amgr，bmgr，mmgr，三个缩写的含义什么？和哪些repo对应？

架构图里面那个词忘记更新了。名称还是以表格里面的为准。那个图片不太好更新。主要体现下架构。

**Comment by elvin-du** [comment]
ipfs-force-community/sophon-bmgr | sophon-miner | .sophon-miner
-- | -- | --


这里的b是什么意思？

**Comment by Fatman13** [comment]
> 这里的b是什么意思？

我的我的，没改。😂

**Comment by hunjixin** [comment]
repo迁移过程  数据目录原则上兼容两个目录一个大版本， 下个大版本已出（或者持续多个）。 最后需要给出一个迁移的注意事项和流程

**Comment by hunjixin** [comment]
https://github.com/filecoin-project/venus/issues/5808

**Comment by LinZexiao** [comment]
编译之后的可执行文件, 统一输出到  ./dist/ 下面
