### ISSUE TITLE
Sprint 61

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5861]
## Background / 背景

Sprint date / Sprint日期：03/27 - 04/07
Github Project：[Venus面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[Cluster面板](https://github.com/orgs/ipfs-force-community/projects/5)，[fvm面板](https://github.com/orgs/ipfs-force-community/projects/7/views/1)
Product release / 版本发布：[计划](https://github.com/filecoin-project/venus/milestones)
> Github Project[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)，代码审阅[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)，代码检查项[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)，文档建立[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)，组件发版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)，需求流程[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E4%BA%A7%E5%93%81%E9%9C%80%E6%B1%82%E7%AE%A1%E7%90%86.md)，设计模版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3%E6%A8%A1%E7%89%88.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5810)

## Theme / 主题

- [x] venus 系统测试（每日编译和测试）（下个sprint hook，异常处理）
- [ ] https://github.com/filecoin-project/venus/issues/5809
- [ ] https://github.com/filecoin-project/venus/issues/5808 
- [ ] 水滴线上问题优化 / https://github.com/filecoin-project/venus/labels/CU-force-community
- [x] Q2 团队目标确定
- [ ] nv19[时间线](https://github.com/filecoin-project/community/discussions/74#discussioncomment-5376097)关注

## ‼️ Maintenance / 重要维护
- [ ] 需求池（点击对应标签，选取`issue`）🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/P1 需求, https://github.com/filecoin-project/venus/labels/P2 需求, https://github.com/filecoin-project/venus/labels/P3 需求（点击标签查看列表） 
  - [ ] https://github.com/filecoin-project/venus/labels/C-Blocked 的`issue`检查是否可以继续执行？
- [ ] `Venus`项目任务维护 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/CU-force-community force任务列表
  - [ ] 链服务/订单服务待评估 https://github.com/filecoin-project/venus/labels/C-triage 任务列表，算力服务[待评估](https://github.com/orgs/ipfs-force-community/projects/5/views/18)任务列表
  - [ ] 给需要测试的`issue`打上 https://github.com/filecoin-project/venus/labels/C-need-testing
  - [ ] https://github.com/filecoin-project/venus/discussions/5769
- [ ] 设计进行中 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus-docs/pull/353 
  - [ ] https://github.com/filecoin-project/venus-docs/pull/346 
- [ ] 团队 
  - [ ] 双数`sprint`对团队目标进行review  

### Project & Ecosystem / 项目&生态

- [x] #5581 （试行中...）
- [ ] https://github.com/filecoin-project/venus/issues/5669

### Chain Service / 链服务

- [x] https://github.com/filecoin-project/venus/issues/5860

### Storage Deal Service / 订单服务

- [x] #5759
- [x] #5851
- [x] #5854
- [x] #5852 
- [x] #5850 
- [x] #5849

### Storage Power Service / 算力服务

- [x] https://github.com/ipfs-force-community/venus-cluster/issues/382
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/663 （review中...）
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/664 （review中...）
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/489 （review中...）
### Storage Service Manager

- [ ] SSM 接入 venus-cluster
- [ ] Dashboard 对接后端数据

### FVM（[milestone](https://github.com/filecoin-project/devgrants/issues/672)）

- [ ] m1.3 验收补充 https://github.com/ipfs-force-community/go-fvm-sdk/issues/114

## Discussion / 讨论

- 开发流程，社区测试流程中遇到的任何问题和困难？🐢 `持续`

**Comment by Fatman13** [comment]
学习计划？

**Comment by Fatman13** [comment]
团队Q2目标。

**Comment by Dio7777777** [comment]
持续交付
