### ISSUE TITLE
Sprint 62

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5893]
## Background / 背景

Sprint date / Sprint日期：04/10 - 04/21
Github Project：[Venus面板](https://github.com/orgs/filecoin-project/projects/51/views/8)，[Cluster面板](https://github.com/orgs/ipfs-force-community/projects/5)，[fvm面板](https://github.com/orgs/ipfs-force-community/projects/7/views/1)
Product release / 版本发布：[计划](https://github.com/filecoin-project/venus/milestones)
> Github Project[文档](https://github.com/ipfs-force-community/dev-guidances/pull/36)，代码审阅[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%AE%A1%E9%98%85.md)，代码检查项[文档](https://github.com/ipfs-force-community/dev-guidances/tree/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E4%BB%A3%E7%A0%81/%E4%BB%A3%E7%A0%81%E5%BA%93/%E6%A3%80%E6%9F%A5%E9%A1%B9)，文档建立[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E8%B4%A8%E9%87%8F%E7%AE%A1%E7%90%86/%E6%96%87%E6%A1%A3/venus-docs%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83.md)，组件发版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E7%AE%A1%E7%90%86.md)，需求流程[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E4%BA%A7%E5%93%81%E9%9C%80%E6%B1%82%E7%AE%A1%E7%90%86.md)，设计模版[文档](https://github.com/ipfs-force-community/dev-guidances/blob/master/%E9%A1%B9%E7%9B%AE%E7%AE%A1%E7%90%86/Venus/%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3%E6%A8%A1%E7%89%88.md)

> 上个 [sprint](https://github.com/filecoin-project/venus/issues/5861)

## Theme / 主题

- [ ] 测试平台功能补充 https://github.com/ipfs-force-community/brightbird/issues
- [ ] https://github.com/filecoin-project/venus/issues/5809
- [ ] 智子服务相关集中优化
- [ ] https://github.com/filecoin-project/venus/issues/5678 （nv19[时间线](https://github.com/filecoin-project/community/discussions/74#discussioncomment-5376097)，venus[时间线](https://github.com/filecoin-project/venus/discussions/5895)）（已经完成大部分，需要等到NV19升级完成才能close）
- [ ] 版本主题规划（改造/升级 https://github.com/filecoin-project/venus/discussions/5468 ）

## ‼️ Maintenance / 重要维护
- [ ] 需求池（点击对应标签，选取`issue`）🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/P1 需求, https://github.com/filecoin-project/venus/labels/P2 需求, https://github.com/filecoin-project/venus/labels/P3 需求（点击标签查看列表） 
  - [ ] https://github.com/filecoin-project/venus/labels/C-Blocked 的`issue`检查是否可以继续执行？
- [ ] `Venus`项目任务维护 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus/labels/CU-force-community force任务列表
  - [ ] 链服务/订单服务待评估 https://github.com/filecoin-project/venus/labels/C-triage 任务列表，算力服务[待评估](https://github.com/orgs/ipfs-force-community/projects/5/views/18)任务列表
  - [ ] 给需要测试的`issue`打上 https://github.com/filecoin-project/venus/labels/C-need-testing
  - [ ] https://github.com/filecoin-project/venus/discussions/5769
- [ ] 设计进行中 🐢 `持续`
  - [ ] https://github.com/filecoin-project/venus-docs/pull/353 
  - [x] https://github.com/filecoin-project/venus-docs/pull/346 
- [ ] 团队 
  - [ ] 双数`sprint`对团队目标进行review  

### Project & Ecosystem / 项目&生态

- [ ] https://github.com/filecoin-project/venus/issues/5669
- [ ] https://github.com/filecoin-project/venus/issues/5808 （Blocked...）

### Chain Service / 链服务

- [x] https://github.com/filecoin-project/venus/issues/5816
- [x] https://github.com/filecoin-project/venus/issues/5891
- [x] https://github.com/filecoin-project/venus/issues/5800
- [x] https://github.com/filecoin-project/venus/issues/5797
- [x] https://github.com/filecoin-project/venus/issues/5796
- [x] https://github.com/filecoin-project/venus/issues/5818
- [x] https://github.com/filecoin-project/venus/issues/5812

### Storage Deal Service / 订单服务

- [x] https://github.com/filecoin-project/venus/issues/5871

### Storage Power Service / 算力服务

- [x] https://github.com/ipfs-force-community/venus-cluster/pull/691
- [x] https://github.com/ipfs-force-community/venus-cluster/pull/687
- [x] https://github.com/ipfs-force-community/venus-cluster/pull/686
- [x] https://github.com/ipfs-force-community/venus-cluster/pull/685
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/663 （50%）
- [ ] https://github.com/filecoin-project/venus/issues/5808
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/389
- [ ] https://github.com/ipfs-force-community/venus-cluster/issues/666 （40%）

### FVM（[milestone](https://github.com/filecoin-project/devgrants/issues/672)）

- [ ] m1.3 验收补充 https://github.com/ipfs-force-community/go-fvm-sdk/issues/114(等待合并)

## Discussion / 讨论

- 开发流程，社区测试流程中遇到的任何问题和困难？🐢 `持续`

**Comment by Fatman13** [comment]
周4总结？

**Comment by Fatman13** [comment]
周四下午总结，周五计划。
