### ISSUE TITLE
[venus] nv21 code tracking and merging / nv21 代码追踪及合并

### ISSUE THREAD

**Issue by simlecode** [filecoin-project/venus#6105]
### Sophon Service / 智子服务

- [X] venus
- [ ] sophon-messager
- [ ] sophon-miner
- [ ] sophon-auth
- [ ] sophon-gateway
- [ ] sophon-co
- [ ] docs / 文档

## nv21 代码追踪及合并

lotus nv20 之后合并的 pr ：[nv21_pr.md](https://github.com/filecoin-project/venus/files/12366838/nv21_pr.md)

### FIP

@0x5459 

https://github.com/filecoin-project/core-devs/discussions/140#discussioncomment-6052418

### hotfix & opt

- [ ] https://github.com/filecoin-project/lotus/pull/11407 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11400 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11398 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11395 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11363 ❓ 

### 依赖

- [ ] https://github.com/filecoin-project/lotus/pull/11428 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11330
- [ ] https://github.com/filecoin-project/lotus/pull/11331
- [ ] https://github.com/filecoin-project/lotus/pull/11333 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11339 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11310 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11312 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11291 ❓ ❗ 
- [ ] https://github.com/filecoin-project/lotus/pull/11221 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11189 ❓ 
- [ ] ~~https://github.com/filecoin-project/lotus/pull/11201 ❓~~
- [ ] https://github.com/filecoin-project/lotus/pull/11164 ❓
- [ ] https://github.com/filecoin-project/lotus/pull/11151 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11146 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11137 ❓ 
- [ ] 11196

### venus 待合并

**venus 代码请向 `feat/nv21` 分支合并**

- [ ] https://github.com/filecoin-project/lotus/pull/11374 
- [ ] https://github.com/filecoin-project/lotus/pull/11344 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11314
- [ ] https://github.com/filecoin-project/lotus/pull/11293 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11203 ❓ (lotus-provider 是啥？)
- [ ] https://github.com/filecoin-project/lotus/pull/11216 ❓ 
- [ ] https://github.com/filecoin-project/lotus/pull/11202 ❓ 
- [x] https://github.com/filecoin-project/lotus/pull/11140 ❓ (UX)
- [ ] ~~https://github.com/filecoin-project/lotus/pull/11149 ❓~~
- [ ] ~~https://github.com/filecoin-project/lotus/pull/11152 ❓~~
- [ ] https://github.com/filecoin-project/lotus/pull/11159 ❓
- [x] 11327
- [x] 11312
- [x] 11310
- [x] 11293
- [x] 11291
- [x] 11258
- [x] 10372
- [x] 11100
- [x] 11215
- [x] 11216
- [x] 11206
- [x] 11167
- [x] #11176
- [ ] ~~#11066~~
- [ ] ~~#11015~~
- [x] #10815
- [ ] ~~#10921~~
- [ ] ~~#10996~~
- [x] #10973
- [x] #10928
- [ ] ~~#10971~~
- [ ] #10941
- [ ] ~~#10937~~
- [x] #10933
- [x] 11016
- [x] 11079
- [ ] ~~11080~~
- [x] 11081
- [x] 11083
- [x] 11158
- [x] 10282

#### 待定

FRC0051: 11104 11157

#### venus 代码合并 

@LinZexiao 

- [ ] ~~#10923~~
- [x]  10650
- [x] #10649
- [ ] ~~#10863~~
- [x] #10879
- [ ] ~~#9070~~
- [x] #10628
- [x] #10652
- [ ] ~~#10894~~
- [x] #10782
- [x] #10719
- [x] #10671
- [x] #10825
- [x] #10534
- [x] #10827
- [ ] ~~#10826~~
- [ ] ~~#10800~~

#### venus 代码合并

@elvin-du 

- [x] #10714  venus 没有tvx命令
- [x] #10680 https://github.com/filecoin-project/venus/issues/6108
- [x] #10713 https://github.com/filecoin-project/venus/issues/6112
- [x] #10636 https://github.com/filecoin-project/venus/pull/6117
- [ ] ~~#10727 release 1.23.0~~
- [ ] ~~#10552~~
- [ ] ~~#10611~~
- [ ] ~~#10544~~
- [x] #10595
- [ ] ~~#10587~~
- [ ] ~~#10535~~
- [ ] #10556
- [ ] #10452
- [ ] ~~#10465~~
- [x] #10282
- [ ] ~~#10390~~
- [ ] ~~#10328~~

### go-jsonrpc 待合并

- [ ] 101
- [ ] 99
- [x] 98  必须要
- [ ] 97

### damocles 待合并

需要评估一下做不做 @0x5459 

- [ ] https://github.com/filecoin-project/lotus/pull/11297 ❓ 
- [x] https://github.com/filecoin-project/lotus/pull/11215 ❓ （切回 PreCommitSectorBatch2？）
- [x] https://github.com/filecoin-project/lotus/pull/11142 ❓ 
- [ ]  ~~https://github.com/filecoin-project/lotus/pull/11145 ❓~~
- [ ] #10923 分组列出将要过期的扇区  [881](https://github.com/ipfs-force-community/damocles/issues/881)
- [ ] #9070  拆分 压缩扇区的 消息，避免一条消息执行会消耗 太多 gas 导致执行失败 [957](https://github.com/ipfs-force-community/damocles/issues/957)
- [ ] ~~#10611~~
- [ ] ~~#10544~~
- [ ] ~~#10390~~
- [ ] ~~#10328~~
- [x] 11301
- [x] 11327

**Comment by Fatman13** [comment]
666666 牛 🐂

**Comment by simlecode** [comment]
事件会有迁移，从当前高度开始，需要看下主网耗时

![image](https://github.com/filecoin-project/venus/assets/69969590/550d6b25-e12d-4787-9e9b-7e2ada3ce9c7)

**Comment by Fatman13** [comment]
11142 好像挺重要的？

![image](https://github.com/filecoin-project/venus/assets/1591330/48766eec-8a7f-4ba6-82f9-2b77b9507bf0)

**Comment by LinZexiao** [comment]
> 11142 好像挺[重要](https://filecoinproject.slack.com/archives/C027TQMUVJN/p1694204364685999)的？
> 
> ![image](https://user-images.githubusercontent.com/1591330/266892391-48766eec-8a7f-4ba6-82f9-2b77b9507bf0.png)

这个相关代码已经创建相关分支，需要在升级前确定是否被包含在升级的代码里面

**Comment by Fatman13** [comment]
actor，fvm，go state 依赖更新；上面列表也添加了。

- [ ] https://github.com/filecoin-project/lotus/pull/11291
