### ISSUE TITLE
[refactor] Remove code duming ground "types"

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/venus#830]
The types package is pretty much a dumping ground where we put type definitions in that we are not sure where to put. We should pull these out and find appropriate places for them to live in. 

- [x] actor -> `actor/actor` #834
- [x] addr_set -> `address/set` #835
- [x] address -> `address/address`#835
- [ ] atto_fil
- [ ] block - > `chain/block` #840
- [ ] block_height -> `chain/block_height`
- [ ] bytes
- [ ] bytes_amount
- [ ] channel_id
- [ ] constants
- [ ] helpers -> `crypto` #840
- [ ] keyinfo -> `crypto/keyinfo` #840
- [ ] message -> `chain/message` #840
- [ ] message_receipt -> `chain/message_receipt` #840
- [ ] recoverer -> `crypto` #840
- [ ] signature -> `crypto/signature` #840
- [ ] signed_message -> `chain/signed_message` #840
- [ ] signer -> `crypto` #840
- [ ] sorted_cid_set
- [ ] testing
- [ ] uint64
