### ISSUE TITLE
manually verify that core flows work 

### ISSUE THREAD

**Issue by phritz** [filecoin-project/venus#953]
This is the canonical place for verifying that things are working for stage 1. We should verify this at several points, checklist included below. Sucks that it's manual, if you want to write some scripts that's great; we will definitely automate this post team week. *This set of "core" user flows should be the first set of true (iptb-based, not testdaemon-based) integration tests that we write.*

## Background

- https://github.com/filecoin-project/go-filecoin/blob/master/README.md#running-filecoin has instructions to run filecoin and instructions for core flows. We want to keep it up do date so please update it if you find something that is off. See also https://github.com/filecoin-project/launch/blob/master/stage-1/test-script.md which is poojaketanshah 's suggested set of command for people to run at team week (aka "user script"); it is WIP
- team week cluster design: https://docs.google.com/document/d/1KuC9chNCC7JKhhc5o5gX7_TzpGLgajfNbJjvXQbtMeg/edit

## Stuff to verify is working

If any of this *does not* work please either address yourself or file a P0 help wanted bug against stage 1 release, put it in this sprint, and try to find someone to work on it.

### Running locally

As you run these tests it would be helpful if you included the commands that you are running to do so below in order to make it easy to repeat the tests. Recall that some commands are given [here](https://github.com/filecoin-project/go-filecoin#sample-commands).

- [x] Verify that things work locally. Start 10 mining nodes [via IPTB](https://github.com/filecoin-project/go-filecoin/blob/master/tools/iptb-plugins/README.md) and:
  - [x] Verify that messages are flooded to all nodes. That is, send a message such as a transfer of FIL and immediately check that all the nodes have it (eg, `iptb run -- go-filecoin mpool` and verify that the message is in every node's message pool) - @frrist 1ae46fff5b3cd7579a3e985213eb6ce1d3dc7974 :heavy_check_mark: 
  - [x] Verify that you can send value (you can send FIL from one account to another, the message gets mined into a block, `wallet balance <address>` shows the amount deducted from the first and added to the second account.) - @frrist 1ae46fff5b3cd7579a3e985213eb6ce1d3dc7974 :heavy_check_mark:
  - [x] Verify that the nodes stay in consensus. All ten of them. If you don't have the dashboard running you can run `iptb run -- go-filecoin chain head` in a loop. - @frrist 1ae46fff5b3cd7579a3e985213eb6ce1d3dc7974 :heavy_check_mark:
  - [x] Verify that as a miner you can add an ask and see it in the orderbook - @frrist 1ae46fff5b3cd7579a3e985213eb6ce1d3dc7974 :heavy_check_mark:
  - [x] Verify that as a client you can make a deal. The only complexity here is that it takes a while to seal and unseal sectors. [This issue](https://github.com/filecoin-project/go-filecoin/issues/961#issuecomment-425766724) should have an answer shortly as to what if any flags/configuration has to be passed to init or the daemon to make sealing and unsealing run quickly for the purposes of testing. Recall some [instructions here](https://github.com/filecoin-project/go-filecoin/blob/master/README.md#sample-commands). - @frrist 1ae46fff5b3cd7579a3e985213eb6ce1d3dc7974 :heavy_check_mark:
  - [x] Verify that as a client you can retrieve a piece that has been sealed. See previous bullet for complexity re sealing and unsealing times. Note that the way this works right now is via `client cat` but will use `retrieval-client` once https://github.com/filecoin-project/go-filecoin/pull/952 lands.- @frrist 1ae46fff5b3cd7579a3e985213eb6ce1d3dc7974 :heavy_check_mark:
  - [x] Verify that creating a miner works. For example run two nodes with iptb, but remove the mining configuration from one. Then [follow the instructions to create a miner on that node](https://github.com/filecoin-project/go-filecoin#sample-commands). Start mining (`mining start`). Make a deal for a file with that miner, verify that it posts a proof on chain. Then verify that once the newly created miner is storing data it occasionally mines a block. This will happen with higher probability with 2 nodes than with 10, which is why I suggested running 2 in this item. - @frrist 1ae46fff5b3cd7579a3e985213eb6ce1d3dc7974 :heavy_check_mark:

### Running against the cluster

A cluster is running at `cluster.kittyhawk.wtf`, not just filecoin nodes but also various support services. See the [designdoc for more detail](https://docs.google.com/document/d/1KuC9chNCC7JKhhc5o5gX7_TzpGLgajfNbJjvXQbtMeg/edit#bookmark=id.xtdh1s5g8r). There is a bunch of work in flight  at the moment (30 Sept 2018) required to get this all working, both on the go-filecoin side and on the infra side.

The task here:
- [ ] Verify that the faucet works. Blocked on: https://github.com/filecoin-project/go-filecoin/issues/960, https://github.com/filecoin-project/go-filecoin/issues/1000, https://github.com/filecoin-project/go-filecoin/issues/919, https://github.com/filecoin-project/go-filecoin/issues/976.
- [ ] Verify the above core workflows work against the test cluster. Blocked on all of the issues in the line above, plus: https://github.com/filecoin-project/go-filecoin/issues/1018, https://github.com/filecoin-project/go-filecoin/issues/961, https://github.com/filecoin-project/go-filecoin/issues/881.
- [ ] Verify that the block explorer works. Blocked on the first two bullets above, plus: https://github.com/filecoin-project/go-filecoin/issues/974, https://github.com/filecoin-project/go-filecoin/issues/956
- [ ] Verify that the visualizer works: blocked on the first two bullets above plus: https://github.com/filecoin-project/go-filecoin/issues/956, https://github.com/filecoin-project/go-filecoin/issues/980, https://github.com/filecoin-project/go-filecoin/issues/977
- [ ]  Verify that the storage market is populated with asks. Blocked on https://github.com/filecoin-project/go-filecoin/issues/982.

### Running against the cluster at scale / time
- [ ] Connect say 80 nodes in to the cluster from several different machines and run through the core flows on a to make sure it works 
- [ ] Leave the cluster alone for 3 hours, then run through the core flows again

## Acceptance Criteria

* Each of the tasks above completes successfully. If you encounter a bug and it is obvious, fix it. If it is not obvious pull whomever has the most state in for a consult and see if they can't quickly point you at how to fix it, and fix it. If it's hairy and someone else should fix it, spin out a P0 for them and make sure they start working on it at highest priority. 
* Add super brief command line instructions for doing what you did above {create miner, add an ask, import a file, propose a storage deal, query storage deal, retrieve the data} to the above. Assume the reader is familiar with filecoin and doesn't need hand-holding or explanations, just get the command lines in there. 
* Update any command lines in https://github.com/filecoin-project/go-filecoin/blob/master/README.md#sample-commands that are wrong. Add any that you think are important that are missing. 

## Who verified what when
* @who verified ${which parts of the above} on ${date} at ${commit}
* ...
